module Peddler
  module Types
    module VendorDirectFulfillmentShipping20211228
      class PackedItem < Data
        def self.new: (item_sequence_number: Integer?, packed_quantity: Peddler::Types::VendorDirectFulfillmentShipping20211228::ItemQuantity?, ?buyer_product_identifier: String?, ?piece_number: Integer?, ?vendor_product_identifier: String?) -> Peddler::Types::VendorDirectFulfillmentShipping20211228::PackedItem
                    | (Integer?, Peddler::Types::VendorDirectFulfillmentShipping20211228::ItemQuantity?, String?, Integer?, String?) -> Peddler::Types::VendorDirectFulfillmentShipping20211228::PackedItem

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorDirectFulfillmentShipping20211228::PackedItem

        attr_reader buyer_product_identifier: String?
        attr_reader item_sequence_number: Integer?
        attr_reader packed_quantity: Peddler::Types::VendorDirectFulfillmentShipping20211228::ItemQuantity?

        attr_reader piece_number: Integer?
        attr_reader vendor_product_identifier: String?

        def to_h: () -> { item_sequence_number: Integer?, packed_quantity: Peddler::Types::VendorDirectFulfillmentShipping20211228::ItemQuantity?, buyer_product_identifier: String?, piece_number: Integer?, vendor_product_identifier: String? }
      end
    end
  end
end
