module Peddler
  module Types
    module VendorDirectFulfillmentShipping20211228
      class Packages < Array[Package]
        def self.parse: (Array[untyped] array) -> instance
      end
    end
  end
end
