module Peddler
  module Types
    module VendorDirectFulfillmentShipping20211228
      class ShipmentDetails < Data
        def self.new: (shipment_status: String?, shipped_date: String?, ?estimated_delivery_date: String?, ?priority_shipment: bool?, ?vendor_order_number: String?) -> Peddler::Types::VendorDirectFulfillmentShipping20211228::ShipmentDetails
                    | (String?, String?, String?, bool?, String?) -> Peddler::Types::VendorDirectFulfillmentShipping20211228::ShipmentDetails

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorDirectFulfillmentShipping20211228::ShipmentDetails

        attr_reader estimated_delivery_date: String?
        attr_reader priority_shipment: bool?
        attr_reader shipment_status: String?
        attr_reader shipped_date: String?

        attr_reader vendor_order_number: String?

        def priority_shipment?: () -> bool
        def to_h: () -> { shipment_status: String?, shipped_date: String?, estimated_delivery_date: String?, priority_shipment: bool?, vendor_order_number: String? }
      end
    end
  end
end
