# frozen_string_literal: true

# This file is generated. Do not edit.

require "structure"
require "time"

module Peddler
  module APIs
    class VendorDirectFulfillmentShippingV1
      # Details about a shipment.
      ShipmentDetails = Structure.new do
        # @return [String] Indicate the shipment status.
        attribute(:shipment_status, String, from: "shipmentStatus")

        # @return [Time] This field indicates the date of the departure of the shipment from vendor's location. Vendors
        # are requested to send ASNs within 30 minutes of departure from their warehouse/distribution center or at least
        # 6 hours prior to the appointment time at the Amazon destination warehouse, whichever is sooner. Shipped date
        # mentioned in the Shipment Confirmation should not be in the future.
        attribute(:shipped_date, Time, from: "shippedDate")

        # @return [Time] Date on which the shipment is expected to reach the buyer's warehouse. It needs to be an
        # estimate based on the average transit time between the ship-from location and the destination. The exact
        # appointment time will be provided by buyer and is potentially not known when creating the shipment
        # confirmation.
        attribute?(:estimated_delivery_date, Time, from: "estimatedDeliveryDate")

        # @return [:boolean] Provide the priority of the shipment.
        attribute?(:priority_shipment, :boolean, from: "isPriorityShipment")

        # @return [String] The vendor order number is a unique identifier generated by a vendor for their reference.
        attribute?(:vendor_order_number, String, from: "vendorOrderNumber")
      end
    end
  end
end
