module Peddler
  module Types
    module ShippingV2
      class CarrierAccountInput < Data
        def self.new: (?description_localization_key: String?, ?group_name: String?, ?input_type: String?, ?confidential: bool?, ?hidden: bool?, ?mandatory: bool?, ?name: String?, ?validation_metadata: Array[Peddler::Types::ShippingV2::ValidationMetadata]?) -> Peddler::Types::ShippingV2::CarrierAccountInput
                    | (String?, String?, String?, bool?, bool?, bool?, String?, Array[Peddler::Types::ShippingV2::ValidationMetadata]?) -> Peddler::Types::ShippingV2::CarrierAccountInput

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ShippingV2::CarrierAccountInput

        attr_reader confidential: bool?
        attr_reader description_localization_key: String?
        attr_reader group_name: String?

        attr_reader hidden: bool?
        attr_reader input_type: String?

        attr_reader mandatory: bool?
        attr_reader name: String?
        attr_reader validation_metadata: Array[Peddler::Types::ShippingV2::ValidationMetadata]?

        def confidential?: () -> bool
        def hidden?: () -> bool
        def mandatory?: () -> bool
        def to_h: () -> { description_localization_key: String?, group_name: String?, input_type: String?, confidential: bool?, hidden: bool?, mandatory: bool?, name: String?, validation_metadata: Array[Peddler::Types::ShippingV2::ValidationMetadata]? }
      end
    end
  end
end
