module Peddler
  module Types
    module ShippingV2
      class CollectOnDelivery < Data
        def self.new: (amount: Peddler::Types::Money?) -> Peddler::Types::ShippingV2::CollectOnDelivery
                    | (Peddler::Types::Money?) -> Peddler::Types::ShippingV2::CollectOnDelivery

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ShippingV2::CollectOnDelivery

        attr_reader amount: Peddler::Types::Money?

        def to_h: () -> { amount: Peddler::Types::Money? }
      end
    end
  end
end
