module Peddler
  module Types
    module ShippingV2
      class DirectPurchaseRequest < Data
        def self.new: (channel_details: Peddler::Types::ShippingV2::ChannelDetails?, ?label_specifications: Peddler::Types::ShippingV2::RequestedDocumentSpecification?, ?packages: Array[Peddler::Types::ShippingV2::Package]?, ?return_to: Peddler::Types::ShippingV2::Address?, ?ship_from: Peddler::Types::ShippingV2::Address?, ?ship_to: Peddler::Types::ShippingV2::Address?) -> Peddler::Types::ShippingV2::DirectPurchaseRequest
                    | (Peddler::Types::ShippingV2::ChannelDetails?, Peddler::Types::ShippingV2::RequestedDocumentSpecification?, Array[Peddler::Types::ShippingV2::Package]?, Peddler::Types::ShippingV2::Address?, Peddler::Types::ShippingV2::Address?, Peddler::Types::ShippingV2::Address?) -> Peddler::Types::ShippingV2::DirectPurchaseRequest

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ShippingV2::DirectPurchaseRequest

        attr_reader channel_details: Peddler::Types::ShippingV2::ChannelDetails?
        attr_reader label_specifications: Peddler::Types::ShippingV2::RequestedDocumentSpecification?
        attr_reader packages: Array[Peddler::Types::ShippingV2::Package]?
        attr_reader return_to: Peddler::Types::ShippingV2::Address?
        attr_reader ship_from: Peddler::Types::ShippingV2::Address?
        attr_reader ship_to: Peddler::Types::ShippingV2::Address?

        def to_h: () -> { channel_details: Peddler::Types::ShippingV2::ChannelDetails?, label_specifications: Peddler::Types::ShippingV2::RequestedDocumentSpecification?, packages: Array[Peddler::Types::ShippingV2::Package]?, return_to: Peddler::Types::ShippingV2::Address?, ship_from: Peddler::Types::ShippingV2::Address?, ship_to: Peddler::Types::ShippingV2::Address? }
      end
    end
  end
end
