module Peddler
  module Types
    module ShippingV2
      class Geocode < Data
        attr_reader latitude: String?
        attr_reader longitude: String?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?latitude: String,
          ?longitude: String
        ) -> void
      end
    end
  end
end
