module Peddler
  module Types
    module ShippingV2
      class LinkableAccountType < Data
        def self.new: (?account_type: String?, ?carrier_account_inputs: Array[Peddler::Types::ShippingV2::CarrierAccountInput]?) -> Peddler::Types::ShippingV2::LinkableAccountType
                    | (String?, Array[Peddler::Types::ShippingV2::CarrierAccountInput]?) -> Peddler::Types::ShippingV2::LinkableAccountType

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ShippingV2::LinkableAccountType

        attr_reader account_type: String?
        attr_reader carrier_account_inputs: Array[Peddler::Types::ShippingV2::CarrierAccountInput]?

        def to_h: () -> { account_type: String?, carrier_account_inputs: Array[Peddler::Types::ShippingV2::CarrierAccountInput]? }
      end
    end
  end
end
