module Peddler
  module Types
    module ShippingV2
      class LinkCarrierAccountResponse < Data
        def self.new: (?account_id: String?, ?registration_status: String?) -> Peddler::Types::ShippingV2::LinkCarrierAccountResponse
                    | (String?, String?) -> Peddler::Types::ShippingV2::LinkCarrierAccountResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ShippingV2::LinkCarrierAccountResponse

        attr_reader account_id: String?
        attr_reader registration_status: String?

        def to_h: () -> { account_id: String?, registration_status: String? }
      end
    end
  end
end
