module Peddler
  module Types
    module ShippingV2
      class LiquidVolume < Data
        def self.new: (unit: String?, value: Float?) -> Peddler::Types::ShippingV2::LiquidVolume
                    | (String?, Float?) -> Peddler::Types::ShippingV2::LiquidVolume

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ShippingV2::LiquidVolume

        attr_reader unit: String?
        attr_reader value: Float?

        def to_h: () -> { unit: String?, value: Float? }
      end
    end
  end
end
