module Peddler
  module Types
    module ShippingV2
      class OneClickShipmentValueAddedServiceDetails < Array[OneClickShipmentValueAddedService]
        def self.parse: (Array[untyped]) -> OneClickShipmentValueAddedServiceDetails
      end
    end
  end
end
