module Peddler
  module Types
    module ShippingV2
      class Rate < Data
        def self.new: (carrier_id: String?, carrier_name: String?, promise: Peddler::Types::ShippingV2::Promise?, rate_id: String?, requires_additional_inputs: bool?, service_id: String?, service_name: String?, supported_document_specifications: Array[Peddler::Types::ShippingV2::SupportedDocumentSpecification]?, total_charge: Peddler::Types::Money?, ?available_value_added_service_groups: Array[Peddler::Types::ShippingV2::AvailableValueAddedServiceGroup]?, ?benefits: Peddler::Types::ShippingV2::Benefits?, ?billed_weight: Peddler::Types::ShippingV2::Weight?, ?payment_type: String?, ?rate_item_list: Array[Peddler::Types::ShippingV2::RateItem]?) -> Peddler::Types::ShippingV2::Rate
                    | (String?, String?, Peddler::Types::ShippingV2::Promise?, String?, bool?, String?, String?, Array[Peddler::Types::ShippingV2::SupportedDocumentSpecification]?, Peddler::Types::Money?, Array[Peddler::Types::ShippingV2::AvailableValueAddedServiceGroup]?, Peddler::Types::ShippingV2::Benefits?, Peddler::Types::ShippingV2::Weight?, String?, Array[Peddler::Types::ShippingV2::RateItem]?) -> Peddler::Types::ShippingV2::Rate

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ShippingV2::Rate

        attr_reader available_value_added_service_groups: Array[Peddler::Types::ShippingV2::AvailableValueAddedServiceGroup]?
        attr_reader benefits: Peddler::Types::ShippingV2::Benefits?
        attr_reader billed_weight: Peddler::Types::ShippingV2::Weight?
        attr_reader carrier_id: String?
        attr_reader carrier_name: String?

        attr_reader payment_type: String?
        attr_reader promise: Peddler::Types::ShippingV2::Promise?
        attr_reader rate_id: String?

        attr_reader rate_item_list: Array[Peddler::Types::ShippingV2::RateItem]?
        attr_reader requires_additional_inputs: bool?
        attr_reader service_id: String?
        attr_reader service_name: String?
        attr_reader supported_document_specifications: Array[Peddler::Types::ShippingV2::SupportedDocumentSpecification]?
        attr_reader total_charge: Peddler::Types::Money?

        def requires_additional_inputs?: () -> bool
        def to_h: () -> { carrier_id: String?, carrier_name: String?, promise: Peddler::Types::ShippingV2::Promise?, rate_id: String?, requires_additional_inputs: bool?, service_id: String?, service_name: String?, supported_document_specifications: Array[Peddler::Types::ShippingV2::SupportedDocumentSpecification]?, total_charge: Peddler::Types::Money?, available_value_added_service_groups: Array[Peddler::Types::ShippingV2::AvailableValueAddedServiceGroup]?, benefits: Peddler::Types::ShippingV2::Benefits?, billed_weight: Peddler::Types::ShippingV2::Weight?, payment_type: String?, rate_item_list: Array[Peddler::Types::ShippingV2::RateItem]? }
      end
    end
  end
end
