module Peddler
  module Types
    module ShippingV2
      class TimeWindow < Data
        attr_reader start: String?
        attr_reader end: String?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?start: String,
          ?end: String
        ) -> void
      end
    end
  end
end
