module Peddler
  module Types
    module ShippingV2
      class TrackingDetailCodes < Data
        def self.new: (forward: Array[untyped]?, returns: Array[untyped]?) -> Peddler::Types::ShippingV2::TrackingDetailCodes
                    | (Array[untyped]?, Array[untyped]?) -> Peddler::Types::ShippingV2::TrackingDetailCodes

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ShippingV2::TrackingDetailCodes

        attr_reader forward: Array[untyped]?
        attr_reader returns: Array[untyped]?

        def to_h: () -> { forward: Array[untyped]?, returns: Array[untyped]? }
      end
    end
  end
end
