# frozen_string_literal: true

require "structure"

module Peddler
  module Types
    module OrdersV0
      # Contains information regarding the Shipping Settings Automation program, such as whether the order's shipping
      # settings were generated automatically, and what those settings are.
      AutomatedShippingSettings = Structure.new do
        # @return [:boolean] When true, this order has automated shipping settings generated by Amazon. This order could
        # be identified as an SSA order.
        attribute(:has_automated_shipping_settings, :boolean, from: "HasAutomatedShippingSettings")

        # @return [String] Auto-generated carrier for SSA orders.
        attribute(:automated_carrier, String, from: "AutomatedCarrier")

        # @return [String] Auto-generated ship method for SSA orders.
        attribute(:automated_ship_method, String, from: "AutomatedShipMethod")
      end
    end
  end
end
