module Peddler
  module Types
    module NotificationsV1
      class ProcessingDirective < Data
        def self.new: (?event_filter: Peddler::Types::NotificationsV1::EventFilter?) -> Peddler::Types::NotificationsV1::ProcessingDirective
                    | (Peddler::Types::NotificationsV1::EventFilter?) -> Peddler::Types::NotificationsV1::ProcessingDirective

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::NotificationsV1::ProcessingDirective

        attr_reader event_filter: Peddler::Types::NotificationsV1::EventFilter?

        def to_h: () -> { event_filter: Peddler::Types::NotificationsV1::EventFilter? }
      end
    end
  end
end
