module Peddler
  module Types
    module VendorDirectFulfillmentShippingV1
      class CustomerInvoiceList < Data
        attr_reader pagination: Pagination?
        attr_reader customer_invoices: Array[CustomerInvoice]?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?pagination: Pagination,
          ?customer_invoices: Array[CustomerInvoice]
        ) -> void
      end
    end
  end
end
