module Peddler
  module Types
    module VendorDirectFulfillmentShippingV1
      class Dimensions < Data
        def self.new: (height: String?, length: String?, unit_of_measure: String?, width: String?) -> Peddler::Types::VendorDirectFulfillmentShippingV1::Dimensions
                    | (String?, String?, String?, String?) -> Peddler::Types::VendorDirectFulfillmentShippingV1::Dimensions

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorDirectFulfillmentShippingV1::Dimensions

        attr_reader height: String?
        attr_reader length: String?
        attr_reader unit_of_measure: String?
        attr_reader width: String?

        def to_h: () -> { height: String?, length: String?, unit_of_measure: String?, width: String? }
      end
    end
  end
end
