module Peddler
  module Types
    module VendorDirectFulfillmentShippingV1
      class GetCustomerInvoiceResponse < Data
        def self.new: (?errors: Array[Peddler::Types::VendorDirectFulfillmentShippingV1::Error]?, ?payload: Peddler::Types::VendorDirectFulfillmentShippingV1::CustomerInvoice?) -> Peddler::Types::VendorDirectFulfillmentShippingV1::GetCustomerInvoiceResponse
                    | (Array[Peddler::Types::VendorDirectFulfillmentShippingV1::Error]?, Peddler::Types::VendorDirectFulfillmentShippingV1::CustomerInvoice?) -> Peddler::Types::VendorDirectFulfillmentShippingV1::GetCustomerInvoiceResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorDirectFulfillmentShippingV1::GetCustomerInvoiceResponse

        attr_reader errors: Array[Peddler::Types::VendorDirectFulfillmentShippingV1::Error]?
        attr_reader payload: Peddler::Types::VendorDirectFulfillmentShippingV1::CustomerInvoice?

        def to_h: () -> { errors: Array[Peddler::Types::VendorDirectFulfillmentShippingV1::Error]?, payload: Peddler::Types::VendorDirectFulfillmentShippingV1::CustomerInvoice? }
      end
    end
  end
end
