module Peddler
  module Types
    module FulfillmentOutbound20200701
      class CreateReturnItem < Data
        attr_reader seller_return_item_id: String
        attr_reader seller_fulfillment_order_item_id: String
        attr_reader amazon_shipment_id: String
        attr_reader return_reason_code: String
        attr_reader return_comment: String?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          seller_return_item_id: String,
          seller_fulfillment_order_item_id: String,
          amazon_shipment_id: String,
          return_reason_code: String,
          ?return_comment: String
        ) -> void
      end
    end
  end
end
