module Peddler
  module Types
    module FulfillmentOutbound20200701
      class DeliveryPreferences < Data
        attr_reader delivery_instructions: String?
        attr_reader drop_off_location: DropOffLocation?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?delivery_instructions: String,
          ?drop_off_location: DropOffLocation
        ) -> void
      end
    end
  end
end
