module Peddler
  module Types
    module FulfillmentOutbound20200701
      class DeliveryDocument < Data
        attr_reader document_type: String
        attr_reader url: String?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          document_type: String,
          ?url: String
        ) -> void
      end
    end
  end
end
