module Peddler
  module Types
    module FulfillmentOutbound20200701
      class ProductIdentifier < Data
        attr_reader merchant_sku: String

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          merchant_sku: String
        ) -> void
      end
    end
  end
end
