module Peddler
  module Types
    module ProductPricingV0
      class CompetitivePriceList < Array[CompetitivePriceType]
        def self.parse: (Array[untyped]) -> CompetitivePriceList
      end
    end
  end
end
