module Peddler
  module Types
    module ProductPricingV0
      class ItemOffersRequestParams < Data
        def self.new: (item_condition: String?, marketplace_id: String?, ?asin: String?, ?customer_type: String?) -> Peddler::Types::ProductPricingV0::ItemOffersRequestParams
                    | (String?, String?, String?, String?) -> Peddler::Types::ProductPricingV0::ItemOffersRequestParams

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ProductPricingV0::ItemOffersRequestParams

        attr_reader asin: String?
        attr_reader customer_type: String?
        attr_reader item_condition: String?
        attr_reader marketplace_id: String?

        def to_h: () -> { item_condition: String?, marketplace_id: String?, asin: String?, customer_type: String? }
      end
    end
  end
end
