module Peddler
  module Types
    module ProductPricingV0
      class ItemOffersResponse < Data
        def self.new: (body: Peddler::Types::ProductPricingV0::GetOffersResponse?, request: Peddler::Types::ProductPricingV0::ItemOffersRequestParams?, ?headers: Hash[untyped, untyped]?, ?status: Peddler::Types::ProductPricingV0::GetOffersHttpStatusLine?) -> Peddler::Types::ProductPricingV0::ItemOffersResponse
                    | (Peddler::Types::ProductPricingV0::GetOffersResponse?, Peddler::Types::ProductPricingV0::ItemOffersRequestParams?, Hash[untyped, untyped]?, Peddler::Types::ProductPricingV0::GetOffersHttpStatusLine?) -> Peddler::Types::ProductPricingV0::ItemOffersResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ProductPricingV0::ItemOffersResponse

        attr_reader body: Peddler::Types::ProductPricingV0::GetOffersResponse?

        attr_reader headers: Hash[untyped, untyped]?
        attr_reader request: Peddler::Types::ProductPricingV0::ItemOffersRequestParams?

        attr_reader status: Peddler::Types::ProductPricingV0::GetOffersHttpStatusLine?

        def to_h: () -> { body: Peddler::Types::ProductPricingV0::GetOffersResponse?, request: Peddler::Types::ProductPricingV0::ItemOffersRequestParams?, headers: Hash[untyped, untyped]?, status: Peddler::Types::ProductPricingV0::GetOffersHttpStatusLine? }
      end
    end
  end
end
