module Peddler
  module Types
    module ProductPricingV0
      class ItemOffersResponseList < Array[ItemOffersResponse]
        def self.parse: (Array[untyped]) -> ItemOffersResponseList
      end
    end
  end
end
