module Peddler
  module Types
    module ProductPricingV0
      class OfferCountType < Data
        attr_reader condition: String?
        attr_reader fulfillment_channel: String?
        attr_reader offer_count: Integer?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?condition: String,
          ?fulfillment_channel: String,
          ?offer_count: Integer
        ) -> void
      end
    end
  end
end
