module Peddler
  module Types
    module ProductPricingV0
      class OfferListingCountType < Data
        def self.new: (count: Integer?, condition: String?) -> Peddler::Types::ProductPricingV0::OfferListingCountType
                    | (Integer?, String?) -> Peddler::Types::ProductPricingV0::OfferListingCountType

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ProductPricingV0::OfferListingCountType

        attr_reader condition: String?
        attr_reader count: Integer?

        def to_h: () -> { count: Integer?, condition: String? }
      end
    end
  end
end
