module Peddler
  module Types
    module ProductPricingV0
      class OfferDetail < Data
        attr_reader my_offer: bool?
        attr_reader offer_type: String?
        attr_reader sub_condition: String
        attr_reader seller_id: String?
        attr_reader condition_notes: String?
        attr_reader seller_feedback_rating: SellerFeedbackType?
        attr_reader shipping_time: DetailedShippingTimeType
        attr_reader listing_price: Money
        attr_reader quantity_discount_prices: Array[QuantityDiscountPriceType]?
        attr_reader points: Points?
        attr_reader shipping: Money
        attr_reader ships_from: ShipsFromType?
        attr_reader fulfilled_by_amazon: bool
        attr_reader prime_information: PrimeInformationType?
        attr_reader buy_box_winner: bool?
        attr_reader featured_merchant: bool?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?my_offer: bool,
          ?offer_type: String,
          sub_condition: String,
          ?seller_id: String,
          ?condition_notes: String,
          ?seller_feedback_rating: SellerFeedbackType,
          shipping_time: DetailedShippingTimeType,
          listing_price: Money,
          ?quantity_discount_prices: Array[QuantityDiscountPriceType],
          ?points: Points,
          shipping: Money,
          ?ships_from: ShipsFromType,
          fulfilled_by_amazon: bool,
          ?prime_information: PrimeInformationType,
          ?buy_box_winner: bool,
          ?featured_merchant: bool
        ) -> void
      end
    end
  end
end
