module Peddler
  module Types
    module ProductPricingV0
      class OfferDetail < Data
        def self.new: (fulfilled_by_amazon: bool?, listing_price: Peddler::Types::Money?, shipping: Peddler::Types::Money?, shipping_time: Peddler::Types::ProductPricingV0::DetailedShippingTimeType?, sub_condition: String?, ?condition_notes: String?, ?buy_box_winner: bool?, ?featured_merchant: bool?, ?my_offer: bool?, ?points: Peddler::Types::ProductPricingV0::Points?, ?prime_information: Peddler::Types::ProductPricingV0::PrimeInformationType?, ?seller_feedback_rating: Peddler::Types::ProductPricingV0::SellerFeedbackType?, ?seller_id: String?, ?ships_from: Peddler::Types::ProductPricingV0::ShipsFromType?, ?offer_type: String?, ?quantity_discount_prices: Array[Peddler::Types::ProductPricingV0::QuantityDiscountPriceType]?) -> Peddler::Types::ProductPricingV0::OfferDetail
                    | (bool?, Peddler::Types::Money?, Peddler::Types::Money?, Peddler::Types::ProductPricingV0::DetailedShippingTimeType?, String?, String?, bool?, bool?, bool?, Peddler::Types::ProductPricingV0::Points?, Peddler::Types::ProductPricingV0::PrimeInformationType?, Peddler::Types::ProductPricingV0::SellerFeedbackType?, String?, Peddler::Types::ProductPricingV0::ShipsFromType?, String?, Array[Peddler::Types::ProductPricingV0::QuantityDiscountPriceType]?) -> Peddler::Types::ProductPricingV0::OfferDetail

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ProductPricingV0::OfferDetail

        attr_reader buy_box_winner: bool?
        attr_reader condition_notes: String?

        attr_reader featured_merchant: bool?
        attr_reader fulfilled_by_amazon: bool?
        attr_reader listing_price: Peddler::Types::Money?

        attr_reader my_offer: bool?

        attr_reader offer_type: String?
        attr_reader points: Peddler::Types::ProductPricingV0::Points?
        attr_reader prime_information: Peddler::Types::ProductPricingV0::PrimeInformationType?

        attr_reader quantity_discount_prices: Array[Peddler::Types::ProductPricingV0::QuantityDiscountPriceType]?
        attr_reader seller_feedback_rating: Peddler::Types::ProductPricingV0::SellerFeedbackType?
        attr_reader seller_id: String?
        attr_reader shipping: Peddler::Types::Money?
        attr_reader shipping_time: Peddler::Types::ProductPricingV0::DetailedShippingTimeType?

        attr_reader ships_from: Peddler::Types::ProductPricingV0::ShipsFromType?
        attr_reader sub_condition: String?

        def buy_box_winner?: () -> bool
        def featured_merchant?: () -> bool
        def fulfilled_by_amazon?: () -> bool

        def my_offer?: () -> bool
        def to_h: () -> { fulfilled_by_amazon: bool?, listing_price: Peddler::Types::Money?, shipping: Peddler::Types::Money?, shipping_time: Peddler::Types::ProductPricingV0::DetailedShippingTimeType?, sub_condition: String?, condition_notes: String?, buy_box_winner: bool?, featured_merchant: bool?, my_offer: bool?, points: Peddler::Types::ProductPricingV0::Points?, prime_information: Peddler::Types::ProductPricingV0::PrimeInformationType?, seller_feedback_rating: Peddler::Types::ProductPricingV0::SellerFeedbackType?, seller_id: String?, ships_from: Peddler::Types::ProductPricingV0::ShipsFromType?, offer_type: String?, quantity_discount_prices: Array[Peddler::Types::ProductPricingV0::QuantityDiscountPriceType]? }
      end
    end
  end
end
