module Peddler
  module Types
    module ExternalFulfillmentReturns20240911
      class InvoiceInformation < Data
        def self.new: (id: String?) -> Peddler::Types::ExternalFulfillmentReturns20240911::InvoiceInformation
                    | (String?) -> Peddler::Types::ExternalFulfillmentReturns20240911::InvoiceInformation

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ExternalFulfillmentReturns20240911::InvoiceInformation

        attr_reader id: String?

        def to_h: () -> { id: String? }
      end
    end
  end
end
