module Peddler
  module Types
    module ExternalFulfillmentReturns20240911
      class OtpDetails < Data
        def self.new: (otp: String?, valid_till: Integer?) -> Peddler::Types::ExternalFulfillmentReturns20240911::OtpDetails
                    | (String?, Integer?) -> Peddler::Types::ExternalFulfillmentReturns20240911::OtpDetails

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ExternalFulfillmentReturns20240911::OtpDetails

        attr_reader otp: String?
        attr_reader valid_till: Integer?

        def to_h: () -> { otp: String?, valid_till: Integer? }
      end
    end
  end
end
