module Peddler
  module Types
    module ExternalFulfillmentReturns20240911
      class ReturnMetadata < Data
        def self.new: (return_reason: String?, ?fulfillment_order_id: String?, ?invoice_information: Peddler::Types::ExternalFulfillmentReturns20240911::InvoiceInformation?, ?rma_id: String?) -> Peddler::Types::ExternalFulfillmentReturns20240911::ReturnMetadata
                    | (String?, String?, Peddler::Types::ExternalFulfillmentReturns20240911::InvoiceInformation?, String?) -> Peddler::Types::ExternalFulfillmentReturns20240911::ReturnMetadata

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ExternalFulfillmentReturns20240911::ReturnMetadata

        attr_reader fulfillment_order_id: String?
        attr_reader invoice_information: Peddler::Types::ExternalFulfillmentReturns20240911::InvoiceInformation?
        attr_reader return_reason: String?

        attr_reader rma_id: String?

        def to_h: () -> { return_reason: String?, fulfillment_order_id: String?, invoice_information: Peddler::Types::ExternalFulfillmentReturns20240911::InvoiceInformation?, rma_id: String? }
      end
    end
  end
end
