module Peddler
  module Types
    module SellerWallet20240301
      class BalanceListing < Data
        def self.new: (?balances: Array[Peddler::Types::SellerWallet20240301::Balance]?) -> Peddler::Types::SellerWallet20240301::BalanceListing
                    | (Array[Peddler::Types::SellerWallet20240301::Balance]?) -> Peddler::Types::SellerWallet20240301::BalanceListing

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::SellerWallet20240301::BalanceListing

        attr_reader balances: Array[Peddler::Types::SellerWallet20240301::Balance]?

        def to_h: () -> { balances: Array[Peddler::Types::SellerWallet20240301::Balance]? }
      end
    end
  end
end
