module Peddler
  module Types
    module SellerWallet20240301
      class Fee < Data
        def self.new: (fee_amount: Peddler::Types::Money?, fee_id: String?, fee_rate_value: String?, fee_type: String?) -> Peddler::Types::SellerWallet20240301::Fee
                    | (Peddler::Types::Money?, String?, String?, String?) -> Peddler::Types::SellerWallet20240301::Fee

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::SellerWallet20240301::Fee

        attr_reader fee_amount: Peddler::Types::Money?
        attr_reader fee_id: String?
        attr_reader fee_rate_value: String?
        attr_reader fee_type: String?

        def to_h: () -> { fee_amount: Peddler::Types::Money?, fee_id: String?, fee_rate_value: String?, fee_type: String? }
      end
    end
  end
end
