module Peddler
  module Types
    module SellerWallet20240301
      class TransferRatePreview < Data
        def self.new: (base_amount: Peddler::Types::Money?, fees: Array[Peddler::Types::SellerWallet20240301::Fee]?, fx_rate_details: Peddler::Types::SellerWallet20240301::FxRateDetails?, transfer_amount: Peddler::Types::Money?) -> Peddler::Types::SellerWallet20240301::TransferRatePreview
                    | (Peddler::Types::Money?, Array[Peddler::Types::SellerWallet20240301::Fee]?, Peddler::Types::SellerWallet20240301::FxRateDetails?, Peddler::Types::Money?) -> Peddler::Types::SellerWallet20240301::TransferRatePreview

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::SellerWallet20240301::TransferRatePreview

        attr_reader base_amount: Peddler::Types::Money?
        attr_reader fees: Array[Peddler::Types::SellerWallet20240301::Fee]?
        attr_reader fx_rate_details: Peddler::Types::SellerWallet20240301::FxRateDetails?
        attr_reader transfer_amount: Peddler::Types::Money?

        def to_h: () -> { base_amount: Peddler::Types::Money?, fees: Array[Peddler::Types::SellerWallet20240301::Fee]?, fx_rate_details: Peddler::Types::SellerWallet20240301::FxRateDetails?, transfer_amount: Peddler::Types::Money? }
      end
    end
  end
end
