module Peddler
  module Types
    module SellerWallet20240301
      class TransactionInstrumentDetails < Data
        def self.new: (account_holder_name: String?, bank_account: Peddler::Types::SellerWallet20240301::BankAccount?, bank_account_number: String?) -> Peddler::Types::SellerWallet20240301::TransactionInstrumentDetails
                    | (String?, Peddler::Types::SellerWallet20240301::BankAccount?, String?) -> Peddler::Types::SellerWallet20240301::TransactionInstrumentDetails

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::SellerWallet20240301::TransactionInstrumentDetails

        attr_reader account_holder_name: String?
        attr_reader bank_account: Peddler::Types::SellerWallet20240301::BankAccount?
        attr_reader bank_account_number: String?

        def to_h: () -> { account_holder_name: String?, bank_account: Peddler::Types::SellerWallet20240301::BankAccount?, bank_account_number: String? }
      end
    end
  end
end
