plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Exclude:
    - "gemfiles/**/*"
  NewCops: enable
  TargetRubyVersion: 3.2
