AllCops:
  Exclude:
    - 'test/helper.rb'
AbcSize:
  Exclude:
    - 'test/**/*'
AccessorMethodName:
  Exclude:
    - 'lib/mws/**/client.rb'
AndOr:
  Enabled: false
ClassLength:
  Exclude:
    - 'test/**/*'
DotPosition:
  EnforcedStyle: leading
Documentation:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Exclude:
    - 'test/**/*'
NestedMethodDefinition:
  Exclude:
    - 'test/**/*'
StringLiterals:
  Enabled: false
