Layout/LineLength:
  Exclude:
    - "test/**/*"
  IgnoredPatterns: ['\A\s*#']
Lint/EmptyBlock:
  Exclude:
    - "Appraisals"
Lint/StructNewOverride:
  Exclude:
    - "test/**/*"
Metrics/AbcSize:
  Exclude:
    - "test/**/*"
Metrics/ClassLength:
  Exclude:
    - "lib/mws/**/client.rb"
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "lib/mws/**/client.rb"
    - "test/**/*"
Metrics/ParameterLists:
  Exclude:
    - "lib/mws/**/client.rb"
Naming/AccessorMethodName:
  Exclude:
    - "lib/mws/**/client.rb"
Naming/VariableNumber:
  Exclude:
    - "test/**/*"
