plugins:
  - rubocop-minitest
  - rubocop-on-rbs
  - rubocop-performance
  - rubocop-rake
inherit_gem:
  rubocop-shopify: rubocop.yml
inherit_from: ".rubocop_todo.yml"

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

RBS:
  Enabled: true
