Layout/LineLength:
  Exclude:
    - "test/**/*"
  IgnoredPatterns: ['\A\s*#']
Metrics/AbcSize:
  Exclude:
    - "test/**/*"
Metrics/ClassLength:
  Exclude:
    - "lib/mws/**/client.rb"
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "lib/mws/**/client.rb"
    - "test/**/*"
Metrics/ParameterLists:
  Exclude:
    - "lib/mws/**/client.rb"
Naming/AccessorMethodName:
  Exclude:
    - "lib/mws/**/client.rb"
