plugins:
  - rubocop-erb
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
inherit_gem:
  rubocop-shopify: rubocop.yml
inherit_from: ".rubocop_todo.yml"

AllCops:
  Exclude:
    - "gemfiles/**/*"
  NewCops: enable
  TargetRubyVersion: 3.2
