Layout/EmptyComment:
  Exclude:
    - "lib/peddler/apis/*.rb"
Layout/LineLength:
  AllowedPatterns:
    - ^\s*\w+ = ".*"$
Lint/ItWithoutArgumentsInBlock:
  Exclude:
    - "test/**/*_test.rb"
Naming/AccessorMethodName:
  Exclude:
    - "lib/peddler/apis/*.rb"
