# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{peddler}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hakan Senol Ensari"]
  s.date = %q{2009-08-15}
  s.description = %q{Peddler is a Ruby wrapper to the Amazon Inventory Management API.}
  s.email = %q{hakan.ensari@papercavalier.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "lib/peddler.rb",
     "lib/peddler/client.rb",
     "lib/peddler/feeds.rb",
     "lib/peddler/handlers.rb",
     "lib/peddler/inventory.rb",
     "lib/peddler/legacy_reports.rb",
     "lib/peddler/refunds.rb",
     "lib/peddler/reports.rb",
     "lib/peddler/transport.rb",
     "peddler.gemspec",
     "spec/peddler/client_spec.rb",
     "spec/peddler/feeds_spec.rb",
     "spec/peddler/handlers_spec.rb",
     "spec/peddler/inventory_spec.rb",
     "spec/peddler/legacy_reports_spec.rb",
     "spec/peddler/refunds_spec.rb",
     "spec/peddler/reports_spec.rb",
     "spec/peddler/transport_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/snl/peddler}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.3}
  s.summary = %q{Peddler is a Ruby wrapper to the Amazon Inventory Management API.}
  s.test_files = [
    "spec/peddler/client_spec.rb",
     "spec/peddler/feeds_spec.rb",
     "spec/peddler/handlers_spec.rb",
     "spec/peddler/inventory_spec.rb",
     "spec/peddler/legacy_reports_spec.rb",
     "spec/peddler/refunds_spec.rb",
     "spec/peddler/reports_spec.rb",
     "spec/peddler/transport_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xmlsimple>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<xmlsimple>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<xmlsimple>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
