module Peddler
  module Types
    module VendorDirectFulfillmentTransactionsV1
      class ErrorList < Array[Error]
        def self.parse: (Array[untyped] array) -> instance
      end
    end
  end
end
