module Peddler
  module Types
    module AplusContent20201101
      class IntegerWithUnits < Data
        def self.new: (units: String?, value: Integer?) -> Peddler::Types::AplusContent20201101::IntegerWithUnits
                    | (String?, Integer?) -> Peddler::Types::AplusContent20201101::IntegerWithUnits

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::AplusContent20201101::IntegerWithUnits

        attr_reader units: String?
        attr_reader value: Integer?

        def to_h: () -> { units: String?, value: Integer? }
      end
    end
  end
end
