module Peddler
  module Types
    module AplusContent20201101
      class PostContentDocumentApprovalSubmissionResponse < Data
        attr_reader warnings: Array[Error]?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?warnings: Array[Error]
        ) -> void
      end
    end
  end
end
