module Peddler
  module Types
    module AplusContent20201101
      class StandardTextListBlock < Data
        def self.new: (text_list: Array[Peddler::Types::AplusContent20201101::TextItem]?) -> Peddler::Types::AplusContent20201101::StandardTextListBlock
                    | (Array[Peddler::Types::AplusContent20201101::TextItem]?) -> Peddler::Types::AplusContent20201101::StandardTextListBlock

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::AplusContent20201101::StandardTextListBlock

        attr_reader text_list: Array[Peddler::Types::AplusContent20201101::TextItem]?

        def to_h: () -> { text_list: Array[Peddler::Types::AplusContent20201101::TextItem]? }
      end
    end
  end
end
