module Peddler
  module Types
    module AplusContent20201101
      class StandardTextBlock < Data
        def self.new: (?body: Peddler::Types::AplusContent20201101::ParagraphComponent?, ?headline: Peddler::Types::AplusContent20201101::TextComponent?) -> Peddler::Types::AplusContent20201101::StandardTextBlock
                    | (Peddler::Types::AplusContent20201101::ParagraphComponent?, Peddler::Types::AplusContent20201101::TextComponent?) -> Peddler::Types::AplusContent20201101::StandardTextBlock

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::AplusContent20201101::StandardTextBlock

        attr_reader body: Peddler::Types::AplusContent20201101::ParagraphComponent?
        attr_reader headline: Peddler::Types::AplusContent20201101::TextComponent?

        def to_h: () -> { body: Peddler::Types::AplusContent20201101::ParagraphComponent?, headline: Peddler::Types::AplusContent20201101::TextComponent? }
      end
    end
  end
end
