module Peddler
  module Types
    module AplusContent20201101
      class TextItem < Data
        attr_reader position: Integer
        attr_reader text: TextComponent

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          position: Integer,
          text: TextComponent
        ) -> void
      end
    end
  end
end
