module Peddler
  module Types
    module SellersV1
      class GetMarketplaceParticipationsResponse < Data
        attr_reader payload: Array[MarketplaceParticipation]?
        attr_reader errors: Array[Error]?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?payload: Array[MarketplaceParticipation],
          ?errors: Array[Error]
        ) -> void
      end
    end
  end
end
