module Peddler
  module Reports
    module B2BProductOpportunitiesNotYetOnAmazonReport20201119
      class Recommendation < Data
        def self.new: (?brand: String?, ?category: String?, ?ean: String?, ?initial_b2b_buyer_industry: String?, ?initial_b2b_buyer_requested_date: String?, ?isbn: String?, ?item_name: String?, ?model_number: String?, ?part_number: String?, ?upc: String?) -> Peddler::Reports::B2BProductOpportunitiesNotYetOnAmazonReport20201119::Recommendation
                    | (String?, String?, String?, String?, String?, String?, String?, String?, String?, String?) -> Peddler::Reports::B2BProductOpportunitiesNotYetOnAmazonReport20201119::Recommendation
        def self.[]: (?brand: String?, ?category: String?, ?ean: String?, ?initial_b2b_buyer_industry: String?, ?initial_b2b_buyer_requested_date: String?, ?isbn: String?, ?item_name: String?, ?model_number: String?, ?part_number: String?, ?upc: String?) -> Peddler::Reports::B2BProductOpportunitiesNotYetOnAmazonReport20201119::Recommendation
                   | (String?, String?, String?, String?, String?, String?, String?, String?, String?, String?) -> Peddler::Reports::B2BProductOpportunitiesNotYetOnAmazonReport20201119::Recommendation

        def self.members: () -> [ :brand, :category, :ean, :initial_b2b_buyer_industry, :initial_b2b_buyer_requested_date, :isbn, :item_name, :model_number, :part_number, :upc ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Reports::B2BProductOpportunitiesNotYetOnAmazonReport20201119::Recommendation

        attr_reader brand: String?
        attr_reader category: String?
        attr_reader ean: String?
        attr_reader initial_b2b_buyer_industry: String?
        attr_reader initial_b2b_buyer_requested_date: String?
        attr_reader isbn: String?
        attr_reader item_name: String?
        attr_reader model_number: String?
        attr_reader part_number: String?
        attr_reader upc: String?

        def members: () -> [ :brand, :category, :ean, :initial_b2b_buyer_industry, :initial_b2b_buyer_requested_date, :isbn, :item_name, :model_number, :part_number, :upc ]
        def to_h: () -> { brand: String?, category: String?, ean: String?, initial_b2b_buyer_industry: String?, initial_b2b_buyer_requested_date: String?, isbn: String?, item_name: String?, model_number: String?, part_number: String?, upc: String? }
      end

      class Report < Data
        def self.new: (recommendations: Array[untyped]) -> Peddler::Reports::B2BProductOpportunitiesNotYetOnAmazonReport20201119::Report
                    | (Array[untyped]) -> Peddler::Reports::B2BProductOpportunitiesNotYetOnAmazonReport20201119::Report
        def self.[]: (recommendations: Array[untyped]) -> Peddler::Reports::B2BProductOpportunitiesNotYetOnAmazonReport20201119::Report
                   | (Array[untyped]) -> Peddler::Reports::B2BProductOpportunitiesNotYetOnAmazonReport20201119::Report

        def self.members: () -> [ :recommendations ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Reports::B2BProductOpportunitiesNotYetOnAmazonReport20201119::Report

        attr_reader recommendations: Array[untyped]

        def members: () -> [ :recommendations ]
        def to_h: () -> { recommendations: Array[untyped] }
      end

      def self.parse: (Hash[String | Symbol, untyped]) -> Peddler::Reports::B2BProductOpportunitiesNotYetOnAmazonReport20201119::Report
    end
  end
end
