module Peddler
  module Types
    module ExternalFulfillmentShipments20240911
      class CourierSupportedAttributes < Data
        def self.new: (carrier_name: String?, tracking_id: String?) -> Peddler::Types::ExternalFulfillmentShipments20240911::CourierSupportedAttributes
                    | (String?, String?) -> Peddler::Types::ExternalFulfillmentShipments20240911::CourierSupportedAttributes

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ExternalFulfillmentShipments20240911::CourierSupportedAttributes

        attr_reader carrier_name: String?
        attr_reader tracking_id: String?

        def to_h: () -> { carrier_name: String?, tracking_id: String? }
      end
    end
  end
end
