module Peddler
  module Types
    module ExternalFulfillmentShipments20240911
      class Dimension < Data
        def self.new: (dimension_unit: String?, value: String?) -> Peddler::Types::ExternalFulfillmentShipments20240911::Dimension
                    | (String?, String?) -> Peddler::Types::ExternalFulfillmentShipments20240911::Dimension

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ExternalFulfillmentShipments20240911::Dimension

        attr_reader dimension_unit: String?
        attr_reader value: String?

        def to_h: () -> { dimension_unit: String?, value: String? }
      end
    end
  end
end
