module Peddler
  module Types
    module ExternalFulfillmentShipments20240911
      class Document < Data
        def self.new: (?content: String?, ?format: String?) -> Peddler::Types::ExternalFulfillmentShipments20240911::Document
                    | (String?, String?) -> Peddler::Types::ExternalFulfillmentShipments20240911::Document

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ExternalFulfillmentShipments20240911::Document

        attr_reader content: String?
        attr_reader format: String?

        def to_h: () -> { content: String?, format: String? }
      end
    end
  end
end
