module Peddler
  module Types
    module ExternalFulfillmentShipments20240911
      class Packages < Data
        def self.new: (packages: Array[Peddler::Types::ExternalFulfillmentShipments20240911::Package]?) -> Peddler::Types::ExternalFulfillmentShipments20240911::Packages
                    | (Array[Peddler::Types::ExternalFulfillmentShipments20240911::Package]?) -> Peddler::Types::ExternalFulfillmentShipments20240911::Packages

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ExternalFulfillmentShipments20240911::Packages

        attr_reader packages: Array[Peddler::Types::ExternalFulfillmentShipments20240911::Package]?

        def to_h: () -> { packages: Array[Peddler::Types::ExternalFulfillmentShipments20240911::Package]? }
      end
    end
  end
end
