module Peddler
  module Types
    module ExternalFulfillmentShipments20240911
      class PackageShipLabel < Data
        def self.new: (?error_details: Peddler::Types::ExternalFulfillmentShipments20240911::Error?, ?file_data: Peddler::Types::ExternalFulfillmentShipments20240911::DocumentV2?, ?package_id: String?, ?ship_label_metadata: Peddler::Types::ExternalFulfillmentShipments20240911::ShipLabelMetadata?, ?status: String?) -> Peddler::Types::ExternalFulfillmentShipments20240911::PackageShipLabel
                    | (Peddler::Types::ExternalFulfillmentShipments20240911::Error?, Peddler::Types::ExternalFulfillmentShipments20240911::DocumentV2?, String?, Peddler::Types::ExternalFulfillmentShipments20240911::ShipLabelMetadata?, String?) -> Peddler::Types::ExternalFulfillmentShipments20240911::PackageShipLabel

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ExternalFulfillmentShipments20240911::PackageShipLabel

        attr_reader error_details: Peddler::Types::ExternalFulfillmentShipments20240911::Error?
        attr_reader file_data: Peddler::Types::ExternalFulfillmentShipments20240911::DocumentV2?
        attr_reader package_id: String?
        attr_reader ship_label_metadata: Peddler::Types::ExternalFulfillmentShipments20240911::ShipLabelMetadata?
        attr_reader status: String?

        def to_h: () -> { error_details: Peddler::Types::ExternalFulfillmentShipments20240911::Error?, file_data: Peddler::Types::ExternalFulfillmentShipments20240911::DocumentV2?, package_id: String?, ship_label_metadata: Peddler::Types::ExternalFulfillmentShipments20240911::ShipLabelMetadata?, status: String? }
      end
    end
  end
end
