module Peddler
  module Types
    module ExternalFulfillmentShipments20240911
      class PartyIdentificationInfo < Data
        def self.new: (party_id: String?, party_type: String?, ?address: Peddler::Types::ExternalFulfillmentShipments20240911::Address?, ?tax_info: Peddler::Types::ExternalFulfillmentShipments20240911::TaxRegistrationInfo?) -> Peddler::Types::ExternalFulfillmentShipments20240911::PartyIdentificationInfo
                    | (String?, String?, Peddler::Types::ExternalFulfillmentShipments20240911::Address?, Peddler::Types::ExternalFulfillmentShipments20240911::TaxRegistrationInfo?) -> Peddler::Types::ExternalFulfillmentShipments20240911::PartyIdentificationInfo

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ExternalFulfillmentShipments20240911::PartyIdentificationInfo

        attr_reader address: Peddler::Types::ExternalFulfillmentShipments20240911::Address?
        attr_reader party_id: String?
        attr_reader party_type: String?

        attr_reader tax_info: Peddler::Types::ExternalFulfillmentShipments20240911::TaxRegistrationInfo?

        def to_h: () -> { party_id: String?, party_type: String?, address: Peddler::Types::ExternalFulfillmentShipments20240911::Address?, tax_info: Peddler::Types::ExternalFulfillmentShipments20240911::TaxRegistrationInfo? }
      end
    end
  end
end
