module Peddler
  module Notifications
    module FulfillmentOrderStatus
      class Amount < Data
        def self.new: (unit: String, value: String) -> Peddler::Notifications::FulfillmentOrderStatus::Amount
                    | (String, String) -> Peddler::Notifications::FulfillmentOrderStatus::Amount
        def self.[]: (unit: String, value: String) -> Peddler::Notifications::FulfillmentOrderStatus::Amount
                   | (String, String) -> Peddler::Notifications::FulfillmentOrderStatus::Amount

        def self.members: () -> [ :unit, :value ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::FulfillmentOrderStatus::Amount

        attr_reader unit: String
        attr_reader value: String

        def members: () -> [ :unit, :value ]
        def to_h: () -> { unit: String, value: String }
      end

      class Money < Data
        def self.new: (amount: String, currency_code: String) -> Peddler::Notifications::FulfillmentOrderStatus::Money
                    | (String, String) -> Peddler::Notifications::FulfillmentOrderStatus::Money
        def self.[]: (amount: String, currency_code: String) -> Peddler::Notifications::FulfillmentOrderStatus::Money
                   | (String, String) -> Peddler::Notifications::FulfillmentOrderStatus::Money

        def self.members: () -> [ :amount, :currency_code ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::FulfillmentOrderStatus::Money

        attr_reader amount: String
        attr_reader currency_code: String

        def members: () -> [ :amount, :currency_code ]
        def to_h: () -> { amount: String, currency_code: String }
      end

      class Notification < Data
        def self.new: (event_time: String, notification_metadata: Hash[untyped, untyped], notification_type: String, notification_version: String, payload: Peddler::Notifications::FulfillmentOrderStatus::Payload, payload_version: String) -> Peddler::Notifications::FulfillmentOrderStatus::Notification
                    | (String, Hash[untyped, untyped], String, String, Peddler::Notifications::FulfillmentOrderStatus::Payload, String) -> Peddler::Notifications::FulfillmentOrderStatus::Notification
        def self.[]: (event_time: String, notification_metadata: Hash[untyped, untyped], notification_type: String, notification_version: String, payload: Peddler::Notifications::FulfillmentOrderStatus::Payload, payload_version: String) -> Peddler::Notifications::FulfillmentOrderStatus::Notification
                   | (String, Hash[untyped, untyped], String, String, Peddler::Notifications::FulfillmentOrderStatus::Payload, String) -> Peddler::Notifications::FulfillmentOrderStatus::Notification

        def self.members: () -> [ :event_time, :notification_metadata, :notification_type, :notification_version, :payload, :payload_version ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::FulfillmentOrderStatus::Notification

        attr_reader event_time: String
        attr_reader notification_metadata: Hash[untyped, untyped]
        attr_reader notification_type: String
        attr_reader notification_version: String
        attr_reader payload: Peddler::Notifications::FulfillmentOrderStatus::Payload
        attr_reader payload_version: String

        def members: () -> [ :event_time, :notification_metadata, :notification_type, :notification_version, :payload, :payload_version ]
        def to_h: () -> { event_time: String, notification_metadata: Hash[untyped, untyped], notification_type: String, notification_version: String, payload: Peddler::Notifications::FulfillmentOrderStatus::Payload, payload_version: String }
      end

      class Payload < Data
        def self.new: (event_type: String, merchant_id: String, order: Hash[untyped, untyped], ?fulfillment_service_id: String?) -> Peddler::Notifications::FulfillmentOrderStatus::Payload
                    | (String, String, Hash[untyped, untyped], String?) -> Peddler::Notifications::FulfillmentOrderStatus::Payload
        def self.[]: (event_type: String, merchant_id: String, order: Hash[untyped, untyped], ?fulfillment_service_id: String?) -> Peddler::Notifications::FulfillmentOrderStatus::Payload
                   | (String, String, Hash[untyped, untyped], String?) -> Peddler::Notifications::FulfillmentOrderStatus::Payload

        def self.members: () -> [ :event_type, :merchant_id, :order, :fulfillment_service_id ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::FulfillmentOrderStatus::Payload

        attr_reader event_type: String
        attr_reader fulfillment_service_id: String?
        attr_reader merchant_id: String
        attr_reader order: Hash[untyped, untyped]

        def members: () -> [ :event_type, :merchant_id, :order, :fulfillment_service_id ]
        def to_h: () -> { event_type: String, merchant_id: String, order: Hash[untyped, untyped], fulfillment_service_id: String? }
      end

      class ProductIdentifier < Data
        def self.new: (amazon_sku: String) -> Peddler::Notifications::FulfillmentOrderStatus::ProductIdentifier
                    | (String) -> Peddler::Notifications::FulfillmentOrderStatus::ProductIdentifier
        def self.[]: (amazon_sku: String) -> Peddler::Notifications::FulfillmentOrderStatus::ProductIdentifier
                   | (String) -> Peddler::Notifications::FulfillmentOrderStatus::ProductIdentifier

        def self.members: () -> [ :amazon_sku ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::FulfillmentOrderStatus::ProductIdentifier

        attr_reader amazon_sku: String

        def members: () -> [ :amazon_sku ]
        def to_h: () -> { amazon_sku: String }
      end

      class Tracking < Data
        def self.new: (?amazon: Hash[untyped, untyped]?, ?carrier: Hash[untyped, untyped]?) -> Peddler::Notifications::FulfillmentOrderStatus::Tracking
                    | (Hash[untyped, untyped]?, Hash[untyped, untyped]?) -> Peddler::Notifications::FulfillmentOrderStatus::Tracking
        def self.[]: (?amazon: Hash[untyped, untyped]?, ?carrier: Hash[untyped, untyped]?) -> Peddler::Notifications::FulfillmentOrderStatus::Tracking
                   | (Hash[untyped, untyped]?, Hash[untyped, untyped]?) -> Peddler::Notifications::FulfillmentOrderStatus::Tracking

        def self.members: () -> [ :amazon, :carrier ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::FulfillmentOrderStatus::Tracking

        attr_reader amazon: Hash[untyped, untyped]?
        attr_reader carrier: Hash[untyped, untyped]?

        def members: () -> [ :amazon, :carrier ]
        def to_h: () -> { amazon: Hash[untyped, untyped]?, carrier: Hash[untyped, untyped]? }
      end

      def self.parse: (Hash[String | Symbol, untyped]) -> Peddler::Notifications::FulfillmentOrderStatus::Notification
    end
  end
end
