module Peddler
  module Notifications
    module ItemSalesEventChange
      class ItemSalesEventChange < Data
        def self.new: (account_id: String?, asin: String?, currency_code: String?, end_time: Time?, marketplace_id: String?, ordered_revenue: Float?, ordered_units: Integer?, start_time: Time?) -> Peddler::Notifications::ItemSalesEventChange::ItemSalesEventChange
                    | (String?, String?, String?, Time?, String?, Float?, Integer?, Time?) -> Peddler::Notifications::ItemSalesEventChange::ItemSalesEventChange
        def self.[]: (account_id: String?, asin: String?, currency_code: String?, end_time: Time?, marketplace_id: String?, ordered_revenue: Float?, ordered_units: Integer?, start_time: Time?) -> Peddler::Notifications::ItemSalesEventChange::ItemSalesEventChange
                   | (String?, String?, String?, Time?, String?, Float?, Integer?, Time?) -> Peddler::Notifications::ItemSalesEventChange::ItemSalesEventChange

        def self.members: () -> [ :account_id, :asin, :currency_code, :end_time, :marketplace_id, :ordered_revenue, :ordered_units, :start_time ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::ItemSalesEventChange::ItemSalesEventChange

        attr_reader account_id: String?
        attr_reader asin: String?
        attr_reader currency_code: String?
        attr_reader end_time: Time?
        attr_reader marketplace_id: String?
        attr_reader ordered_revenue: Float?
        attr_reader ordered_units: Integer?
        attr_reader start_time: Time?

        def members: () -> [ :account_id, :asin, :currency_code, :end_time, :marketplace_id, :ordered_revenue, :ordered_units, :start_time ]
        def to_h: () -> { account_id: String?, asin: String?, currency_code: String?, end_time: Time?, marketplace_id: String?, ordered_revenue: Float?, ordered_units: Integer?, start_time: Time? }
      end

      class ItemSalesEventChanges < Array[ItemSalesEventChange]
        def self.parse: (Array[untyped]) -> ItemSalesEventChanges
      end

      class Notification < Data
        def self.new: (event_time: String?, notification_metadata: String?, notification_type: String?, notification_version: String?, payload: Peddler::Notifications::ItemSalesEventChange::Payload?, payload_version: String?) -> Peddler::Notifications::ItemSalesEventChange::Notification
                    | (String?, String?, String?, String?, Peddler::Notifications::ItemSalesEventChange::Payload?, String?) -> Peddler::Notifications::ItemSalesEventChange::Notification
        def self.[]: (event_time: String?, notification_metadata: String?, notification_type: String?, notification_version: String?, payload: Peddler::Notifications::ItemSalesEventChange::Payload?, payload_version: String?) -> Peddler::Notifications::ItemSalesEventChange::Notification
                   | (String?, String?, String?, String?, Peddler::Notifications::ItemSalesEventChange::Payload?, String?) -> Peddler::Notifications::ItemSalesEventChange::Notification

        def self.members: () -> [ :event_time, :notification_metadata, :notification_type, :notification_version, :payload, :payload_version ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::ItemSalesEventChange::Notification

        attr_reader event_time: String?
        attr_reader notification_metadata: String?
        attr_reader notification_type: String?
        attr_reader notification_version: String?
        attr_reader payload: Peddler::Notifications::ItemSalesEventChange::Payload?
        attr_reader payload_version: String?

        def members: () -> [ :event_time, :notification_metadata, :notification_type, :notification_version, :payload, :payload_version ]
        def to_h: () -> { event_time: String?, notification_metadata: String?, notification_type: String?, notification_version: String?, payload: Peddler::Notifications::ItemSalesEventChange::Payload?, payload_version: String? }
      end

      class NotificationMetadata < Data
        def self.new: (application_id: String?, notification_id: String?, publish_time: String?, subscription_id: String?) -> Peddler::Notifications::ItemSalesEventChange::NotificationMetadata
                    | (String?, String?, String?, String?) -> Peddler::Notifications::ItemSalesEventChange::NotificationMetadata
        def self.[]: (application_id: String?, notification_id: String?, publish_time: String?, subscription_id: String?) -> Peddler::Notifications::ItemSalesEventChange::NotificationMetadata
                   | (String?, String?, String?, String?) -> Peddler::Notifications::ItemSalesEventChange::NotificationMetadata

        def self.members: () -> [ :application_id, :notification_id, :publish_time, :subscription_id ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::ItemSalesEventChange::NotificationMetadata

        attr_reader application_id: String?
        attr_reader notification_id: String?
        attr_reader publish_time: String?
        attr_reader subscription_id: String?

        def members: () -> [ :application_id, :notification_id, :publish_time, :subscription_id ]
        def to_h: () -> { application_id: String?, notification_id: String?, publish_time: String?, subscription_id: String? }
      end

      class Payload < Data
        def self.new: (item_sales_event_changes: Array[Peddler::Notifications::ItemSalesEventChange::ItemSalesEventChange]?) -> Peddler::Notifications::ItemSalesEventChange::Payload
                    | (Array[Peddler::Notifications::ItemSalesEventChange::ItemSalesEventChange]?) -> Peddler::Notifications::ItemSalesEventChange::Payload
        def self.[]: (item_sales_event_changes: Array[Peddler::Notifications::ItemSalesEventChange::ItemSalesEventChange]?) -> Peddler::Notifications::ItemSalesEventChange::Payload
                   | (Array[Peddler::Notifications::ItemSalesEventChange::ItemSalesEventChange]?) -> Peddler::Notifications::ItemSalesEventChange::Payload

        def self.members: () -> [ :item_sales_event_changes ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::ItemSalesEventChange::Payload

        attr_reader item_sales_event_changes: Array[Peddler::Notifications::ItemSalesEventChange::ItemSalesEventChange]?

        def members: () -> [ :item_sales_event_changes ]
        def to_h: () -> { item_sales_event_changes: Array[Peddler::Notifications::ItemSalesEventChange::ItemSalesEventChange]? }
      end

      def self.parse: (Hash[String | Symbol, untyped]) -> Peddler::Notifications::ItemSalesEventChange::Notification
    end
  end
end
