module Peddler
  module Notifications
    module TaxInvoiceIssuanceStatus
      class Notification < Data
        def self.new: (event_time: String, notification_metadata: String, notification_type: String, notification_version: String, payload: Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload, payload_version: String) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Notification
                    | (String, String, String, String, Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload, String) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Notification
        def self.[]: (event_time: String, notification_metadata: String, notification_type: String, notification_version: String, payload: Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload, payload_version: String) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Notification
                   | (String, String, String, String, Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload, String) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Notification

        def self.members: () -> [ :event_time, :notification_metadata, :notification_type, :notification_version, :payload, :payload_version ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Notification

        attr_reader event_time: String
        attr_reader notification_metadata: String
        attr_reader notification_type: String
        attr_reader notification_version: String
        attr_reader payload: Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload
        attr_reader payload_version: String

        def members: () -> [ :event_time, :notification_metadata, :notification_type, :notification_version, :payload, :payload_version ]
        def to_h: () -> { event_time: String, notification_metadata: String, notification_type: String, notification_version: String, payload: Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload, payload_version: String }
      end

      class Notification < Data
        def self.new: (event_time: String, notification_metadata: String, notification_type: String, notification_version: String, payload: Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload, payload_version: String) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Notification
                    | (String, String, String, String, Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload, String) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Notification
        def self.[]: (event_time: String, notification_metadata: String, notification_type: String, notification_version: String, payload: Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload, payload_version: String) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Notification
                   | (String, String, String, String, Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload, String) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Notification

        def self.members: () -> [ :event_time, :notification_metadata, :notification_type, :notification_version, :payload, :payload_version ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Notification

        attr_reader event_time: String
        attr_reader notification_metadata: String
        attr_reader notification_type: String
        attr_reader notification_version: String
        attr_reader payload: Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload
        attr_reader payload_version: String

        def members: () -> [ :event_time, :notification_metadata, :notification_type, :notification_version, :payload, :payload_version ]
        def to_h: () -> { event_time: String, notification_metadata: String, notification_type: String, notification_version: String, payload: Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload, payload_version: String }
      end

      class NotificationMetadata < Data
        def self.new: (application_id: String, notification_id: String, publish_time: String, subscription_id: String) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::NotificationMetadata
                    | (String, String, String, String) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::NotificationMetadata
        def self.[]: (application_id: String, notification_id: String, publish_time: String, subscription_id: String) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::NotificationMetadata
                   | (String, String, String, String) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::NotificationMetadata

        def self.members: () -> [ :application_id, :notification_id, :publish_time, :subscription_id ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::NotificationMetadata

        attr_reader application_id: String
        attr_reader notification_id: String
        attr_reader publish_time: String
        attr_reader subscription_id: String

        def members: () -> [ :application_id, :notification_id, :publish_time, :subscription_id ]
        def to_h: () -> { application_id: String, notification_id: String, publish_time: String, subscription_id: String }
      end

      class Payload < Data
        def self.new: (date: Time, invoice_id: String, marketplace_id: String, status: String, ?error: Hash[untyped, untyped]?, ?order_id: String?) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload
                    | (Time, String, String, String, Hash[untyped, untyped]?, String?) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload
        def self.[]: (date: Time, invoice_id: String, marketplace_id: String, status: String, ?error: Hash[untyped, untyped]?, ?order_id: String?) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload
                   | (Time, String, String, String, Hash[untyped, untyped]?, String?) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload

        def self.members: () -> [ :date, :invoice_id, :marketplace_id, :status, :error, :order_id ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Payload

        attr_reader date: Time
        attr_reader error: Hash[untyped, untyped]?
        attr_reader invoice_id: String
        attr_reader marketplace_id: String
        attr_reader order_id: String?
        attr_reader status: String

        def members: () -> [ :date, :invoice_id, :marketplace_id, :status, :error, :order_id ]
        def to_h: () -> { date: Time, invoice_id: String, marketplace_id: String, status: String, error: Hash[untyped, untyped]?, order_id: String? }
      end

      def self.parse: (Hash[String | Symbol, untyped]) -> Peddler::Notifications::TaxInvoiceIssuanceStatus::Notification
    end
  end
end
