module Peddler
  module Types
    module AmazonWarehousingAndDistribution20240509
      class DestinationDetails < Data
        def self.new: (?destination_address: Peddler::Types::AmazonWarehousingAndDistribution20240509::Address?, ?destination_region: String?, ?shipment_id: String?) -> Peddler::Types::AmazonWarehousingAndDistribution20240509::DestinationDetails
                    | (Peddler::Types::AmazonWarehousingAndDistribution20240509::Address?, String?, String?) -> Peddler::Types::AmazonWarehousingAndDistribution20240509::DestinationDetails

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::AmazonWarehousingAndDistribution20240509::DestinationDetails

        attr_reader destination_address: Peddler::Types::AmazonWarehousingAndDistribution20240509::Address?
        attr_reader destination_region: String?
        attr_reader shipment_id: String?

        def to_h: () -> { destination_address: Peddler::Types::AmazonWarehousingAndDistribution20240509::Address?, destination_region: String?, shipment_id: String? }
      end
    end
  end
end
