module Peddler
  module Types
    module AmazonWarehousingAndDistribution20240509
      class InboundOrderCreationData < Data
        def self.new: (origin_address: Peddler::Types::AmazonWarehousingAndDistribution20240509::Address?, packages_to_inbound: Array[Peddler::Types::AmazonWarehousingAndDistribution20240509::DistributionPackageQuantity]?, ?external_reference_id: String?, ?preferences: Peddler::Types::AmazonWarehousingAndDistribution20240509::InboundPreferences?) -> Peddler::Types::AmazonWarehousingAndDistribution20240509::InboundOrderCreationData
                    | (Peddler::Types::AmazonWarehousingAndDistribution20240509::Address?, Array[Peddler::Types::AmazonWarehousingAndDistribution20240509::DistributionPackageQuantity]?, String?, Peddler::Types::AmazonWarehousingAndDistribution20240509::InboundPreferences?) -> Peddler::Types::AmazonWarehousingAndDistribution20240509::InboundOrderCreationData

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::AmazonWarehousingAndDistribution20240509::InboundOrderCreationData

        attr_reader external_reference_id: String?
        attr_reader origin_address: Peddler::Types::AmazonWarehousingAndDistribution20240509::Address?
        attr_reader packages_to_inbound: Array[Peddler::Types::AmazonWarehousingAndDistribution20240509::DistributionPackageQuantity]?

        attr_reader preferences: Peddler::Types::AmazonWarehousingAndDistribution20240509::InboundPreferences?

        def to_h: () -> { origin_address: Peddler::Types::AmazonWarehousingAndDistribution20240509::Address?, packages_to_inbound: Array[Peddler::Types::AmazonWarehousingAndDistribution20240509::DistributionPackageQuantity]?, external_reference_id: String?, preferences: Peddler::Types::AmazonWarehousingAndDistribution20240509::InboundPreferences? }
      end
    end
  end
end
