module Peddler
  module Types
    module AmazonWarehousingAndDistribution20240509
      class InventorySummary < Data
        def self.new: (sku: String?, ?expiration_details: Array[Peddler::Types::AmazonWarehousingAndDistribution20240509::ExpirationDetails]?, ?inventory_details: Peddler::Types::AmazonWarehousingAndDistribution20240509::InventoryDetails?, ?total_inbound_quantity: Integer?, ?total_onhand_quantity: Integer?) -> Peddler::Types::AmazonWarehousingAndDistribution20240509::InventorySummary
                    | (String?, Array[Peddler::Types::AmazonWarehousingAndDistribution20240509::ExpirationDetails]?, Peddler::Types::AmazonWarehousingAndDistribution20240509::InventoryDetails?, Integer?, Integer?) -> Peddler::Types::AmazonWarehousingAndDistribution20240509::InventorySummary

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::AmazonWarehousingAndDistribution20240509::InventorySummary

        attr_reader expiration_details: Array[Peddler::Types::AmazonWarehousingAndDistribution20240509::ExpirationDetails]?
        attr_reader inventory_details: Peddler::Types::AmazonWarehousingAndDistribution20240509::InventoryDetails?
        attr_reader sku: String?

        attr_reader total_inbound_quantity: Integer?
        attr_reader total_onhand_quantity: Integer?

        def to_h: () -> { sku: String?, expiration_details: Array[Peddler::Types::AmazonWarehousingAndDistribution20240509::ExpirationDetails]?, inventory_details: Peddler::Types::AmazonWarehousingAndDistribution20240509::InventoryDetails?, total_inbound_quantity: Integer?, total_onhand_quantity: Integer? }
      end
    end
  end
end
