module Peddler
  module Types
    module AmazonWarehousingAndDistribution20240509
      class SkuEligibility < Data
        attr_reader ineligibility_reasons: Array[SkuIneligibilityReason]?
        attr_reader package_quantity: DistributionPackageQuantity
        attr_reader status: String

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?ineligibility_reasons: Array[SkuIneligibilityReason],
          package_quantity: DistributionPackageQuantity,
          status: String
        ) -> void
      end
    end
  end
end
