module Peddler
  module Types
    module AmazonWarehousingAndDistribution20240509
      class SkuQuantity < Data
        def self.new: (expected_quantity: Peddler::Types::AmazonWarehousingAndDistribution20240509::InventoryQuantity?, sku: String?, ?received_quantity: Peddler::Types::AmazonWarehousingAndDistribution20240509::InventoryQuantity?) -> Peddler::Types::AmazonWarehousingAndDistribution20240509::SkuQuantity
                    | (Peddler::Types::AmazonWarehousingAndDistribution20240509::InventoryQuantity?, String?, Peddler::Types::AmazonWarehousingAndDistribution20240509::InventoryQuantity?) -> Peddler::Types::AmazonWarehousingAndDistribution20240509::SkuQuantity

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::AmazonWarehousingAndDistribution20240509::SkuQuantity

        attr_reader expected_quantity: Peddler::Types::AmazonWarehousingAndDistribution20240509::InventoryQuantity?

        attr_reader received_quantity: Peddler::Types::AmazonWarehousingAndDistribution20240509::InventoryQuantity?
        attr_reader sku: String?

        def to_h: () -> { expected_quantity: Peddler::Types::AmazonWarehousingAndDistribution20240509::InventoryQuantity?, sku: String?, received_quantity: Peddler::Types::AmazonWarehousingAndDistribution20240509::InventoryQuantity? }
      end
    end
  end
end
