module Peddler
  module Types
    module VendorDirectFulfillmentSandboxTestData20211028
      class Scenario < Data
        def self.new: (orders: Array[Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::TestOrder]?, scenario_id: String?) -> Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::Scenario
                    | (Array[Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::TestOrder]?, String?) -> Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::Scenario

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::Scenario

        attr_reader orders: Array[Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::TestOrder]?
        attr_reader scenario_id: String?

        def to_h: () -> { orders: Array[Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::TestOrder]?, scenario_id: String? }
      end
    end
  end
end
