module Peddler
  module Types
    module VendorDirectFulfillmentSandboxTestData20211028
      class Transaction < Data
        def self.new: (status: String?, transaction_id: String?, ?test_case_data: Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::TestCaseData?) -> Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::Transaction
                    | (String?, String?, Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::TestCaseData?) -> Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::Transaction

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::Transaction

        attr_reader status: String?

        attr_reader test_case_data: Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::TestCaseData?
        attr_reader transaction_id: String?

        def to_h: () -> { status: String?, transaction_id: String?, test_case_data: Peddler::Types::VendorDirectFulfillmentSandboxTestData20211028::TestCaseData? }
      end
    end
  end
end
