module Peddler
  module Types
    module MessagingV1
      class CreateWarrantyRequest < Data
        attr_reader attachments: Array[Attachment]?
        attr_reader coverage_start_date: String?
        attr_reader coverage_end_date: String?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?attachments: Array[Attachment],
          ?coverage_start_date: String,
          ?coverage_end_date: String
        ) -> void
      end
    end
  end
end
