module Peddler
  module Types
    module MessagingV1
      class GetMessagingActionsForOrderResponse < Data
        attr_reader _links: Hash[String, untyped]?
        attr_reader _embedded: Hash[String, untyped]?
        attr_reader errors: Array[Error]?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?_links: Hash[String, untyped],
          ?_embedded: Hash[String, untyped],
          ?errors: Array[Error]
        ) -> void
      end
    end
  end
end
