module Peddler
  module Types
    module Transfers20240601
      class ErrorList < Data
        def self.new: (errors: Array[Peddler::Types::Transfers20240601::Error]?) -> Peddler::Types::Transfers20240601::ErrorList
                    | (Array[Peddler::Types::Transfers20240601::Error]?) -> Peddler::Types::Transfers20240601::ErrorList

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::Transfers20240601::ErrorList

        attr_reader errors: Array[Peddler::Types::Transfers20240601::Error]?

        def to_h: () -> { errors: Array[Peddler::Types::Transfers20240601::Error]? }
      end
    end
  end
end
