module Peddler
  module Types
    module CustomerFeedback20240601
      class BrowseNodeReturnTrendsResponse < Data
        attr_reader browse_node_id: String
        attr_reader display_name: String
        attr_reader marketplace_id: String
        attr_reader country_code: String
        attr_reader date_range: DateRange
        attr_reader return_trends: Array[BrowseNodeReturnTrend]

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          browse_node_id: String,
          display_name: String,
          marketplace_id: String,
          country_code: String,
          date_range: DateRange,
          return_trends: Array[BrowseNodeReturnTrend]
        ) -> void
      end
    end
  end
end
