module Peddler
  module Types
    module CustomerFeedback20240601
      class BrowseNodeOccurrence < Data
        def self.new: (all_products: Float?) -> Peddler::Types::CustomerFeedback20240601::BrowseNodeOccurrence
                    | (Float?) -> Peddler::Types::CustomerFeedback20240601::BrowseNodeOccurrence

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::CustomerFeedback20240601::BrowseNodeOccurrence

        attr_reader all_products: Float?

        def to_h: () -> { all_products: Float? }
      end
    end
  end
end
