module Peddler
  module Types
    module CustomerFeedback20240601
      class BrowseNodeReturnTrendPoint < Data
        def self.new: (browse_node_metrics: Peddler::Types::CustomerFeedback20240601::BrowseNodeTrendMetrics?, date_range: Peddler::Types::CustomerFeedback20240601::DateRange?) -> Peddler::Types::CustomerFeedback20240601::BrowseNodeReturnTrendPoint
                    | (Peddler::Types::CustomerFeedback20240601::BrowseNodeTrendMetrics?, Peddler::Types::CustomerFeedback20240601::DateRange?) -> Peddler::Types::CustomerFeedback20240601::BrowseNodeReturnTrendPoint

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::CustomerFeedback20240601::BrowseNodeReturnTrendPoint

        attr_reader browse_node_metrics: Peddler::Types::CustomerFeedback20240601::BrowseNodeTrendMetrics?
        attr_reader date_range: Peddler::Types::CustomerFeedback20240601::DateRange?

        def to_h: () -> { browse_node_metrics: Peddler::Types::CustomerFeedback20240601::BrowseNodeTrendMetrics?, date_range: Peddler::Types::CustomerFeedback20240601::DateRange? }
      end
    end
  end
end
