module Peddler
  module Types
    module CustomerFeedback20240601
      class BrowseNodeSubtopic < Data
        def self.new: (metrics: Peddler::Types::CustomerFeedback20240601::BrowseNodeReviewSubtopicMetrics?, subtopic: String?, ?review_snippets: Array[String]?) -> Peddler::Types::CustomerFeedback20240601::BrowseNodeSubtopic
                    | (Peddler::Types::CustomerFeedback20240601::BrowseNodeReviewSubtopicMetrics?, String?, Array[String]?) -> Peddler::Types::CustomerFeedback20240601::BrowseNodeSubtopic

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::CustomerFeedback20240601::BrowseNodeSubtopic

        attr_reader metrics: Peddler::Types::CustomerFeedback20240601::BrowseNodeReviewSubtopicMetrics?

        attr_reader review_snippets: Array[String]?
        attr_reader subtopic: String?

        def to_h: () -> { metrics: Peddler::Types::CustomerFeedback20240601::BrowseNodeReviewSubtopicMetrics?, subtopic: String?, review_snippets: Array[String]? }
      end
    end
  end
end
