module Peddler
  module Types
    module CustomerFeedback20240601
      class DateRange < Data
        def self.new: (end_date: String?, start_date: String?) -> Peddler::Types::CustomerFeedback20240601::DateRange
                    | (String?, String?) -> Peddler::Types::CustomerFeedback20240601::DateRange

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::CustomerFeedback20240601::DateRange

        attr_reader end_date: String?
        attr_reader start_date: String?

        def to_h: () -> { end_date: String?, start_date: String? }
      end
    end
  end
end
