module Peddler
  module Types
    module FulfillmentInboundV0
      class SKUPrepInstructionsList < Array[SKUPrepInstructions]
        def self.parse: (Array[untyped]) -> SKUPrepInstructionsList
      end
    end
  end
end
