module Peddler
  module Types
    module VendorOrdersV1
      class GetPurchaseOrdersResponse < Data
        def self.new: (?errors: Array[Peddler::Types::VendorOrdersV1::Error]?, ?payload: Peddler::Types::VendorOrdersV1::OrderList?) -> Peddler::Types::VendorOrdersV1::GetPurchaseOrdersResponse
                    | (Array[Peddler::Types::VendorOrdersV1::Error]?, Peddler::Types::VendorOrdersV1::OrderList?) -> Peddler::Types::VendorOrdersV1::GetPurchaseOrdersResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorOrdersV1::GetPurchaseOrdersResponse

        attr_reader errors: Array[Peddler::Types::VendorOrdersV1::Error]?
        attr_reader payload: Peddler::Types::VendorOrdersV1::OrderList?

        def to_h: () -> { errors: Array[Peddler::Types::VendorOrdersV1::Error]?, payload: Peddler::Types::VendorOrdersV1::OrderList? }
      end
    end
  end
end
