module Peddler
  module Types
    module VendorOrdersV1
      class GetPurchaseOrderResponse < Data
        def self.new: (?errors: Array[Peddler::Types::VendorOrdersV1::Error]?, ?payload: Peddler::Types::VendorOrdersV1::Order?) -> Peddler::Types::VendorOrdersV1::GetPurchaseOrderResponse
                    | (Array[Peddler::Types::VendorOrdersV1::Error]?, Peddler::Types::VendorOrdersV1::Order?) -> Peddler::Types::VendorOrdersV1::GetPurchaseOrderResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorOrdersV1::GetPurchaseOrderResponse

        attr_reader errors: Array[Peddler::Types::VendorOrdersV1::Error]?
        attr_reader payload: Peddler::Types::VendorOrdersV1::Order?

        def to_h: () -> { errors: Array[Peddler::Types::VendorOrdersV1::Error]?, payload: Peddler::Types::VendorOrdersV1::Order? }
      end
    end
  end
end
