module Peddler
  module Types
    module VendorOrdersV1
      class ImportDetails < Data
        def self.new: (?import_containers: String?, ?international_commercial_terms: String?, ?method_of_payment: String?, ?port_of_delivery: String?, ?shipping_instructions: String?) -> Peddler::Types::VendorOrdersV1::ImportDetails
                    | (String?, String?, String?, String?, String?) -> Peddler::Types::VendorOrdersV1::ImportDetails

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorOrdersV1::ImportDetails

        attr_reader import_containers: String?
        attr_reader international_commercial_terms: String?
        attr_reader method_of_payment: String?
        attr_reader port_of_delivery: String?
        attr_reader shipping_instructions: String?

        def to_h: () -> { import_containers: String?, international_commercial_terms: String?, method_of_payment: String?, port_of_delivery: String?, shipping_instructions: String? }
      end
    end
  end
end
