module Peddler
  module Types
    module VendorOrdersV1
      class OrderList < Data
        def self.new: (?orders: Array[Peddler::Types::VendorOrdersV1::Order]?, ?pagination: Peddler::Types::VendorOrdersV1::Pagination?) -> Peddler::Types::VendorOrdersV1::OrderList
                    | (Array[Peddler::Types::VendorOrdersV1::Order]?, Peddler::Types::VendorOrdersV1::Pagination?) -> Peddler::Types::VendorOrdersV1::OrderList

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorOrdersV1::OrderList

        attr_reader orders: Array[Peddler::Types::VendorOrdersV1::Order]?
        attr_reader pagination: Peddler::Types::VendorOrdersV1::Pagination?

        def to_h: () -> { orders: Array[Peddler::Types::VendorOrdersV1::Order]?, pagination: Peddler::Types::VendorOrdersV1::Pagination? }
      end
    end
  end
end
