module Peddler
  module Types
    module VendorOrdersV1
      class OrderListStatus < Data
        def self.new: (?orders_status: Array[Peddler::Types::VendorOrdersV1::OrderStatus]?, ?pagination: Peddler::Types::VendorOrdersV1::Pagination?) -> Peddler::Types::VendorOrdersV1::OrderListStatus
                    | (Array[Peddler::Types::VendorOrdersV1::OrderStatus]?, Peddler::Types::VendorOrdersV1::Pagination?) -> Peddler::Types::VendorOrdersV1::OrderListStatus

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorOrdersV1::OrderListStatus

        attr_reader orders_status: Array[Peddler::Types::VendorOrdersV1::OrderStatus]?
        attr_reader pagination: Peddler::Types::VendorOrdersV1::Pagination?

        def to_h: () -> { orders_status: Array[Peddler::Types::VendorOrdersV1::OrderStatus]?, pagination: Peddler::Types::VendorOrdersV1::Pagination? }
      end
    end
  end
end
