# frozen_string_literal: true

module Peddler
  module Types
    class Money < Data
      attr_reader amount: String
      attr_reader currency_code: String

      def self.new: (amount: String, currency_code: String) -> Money
      def self.parse: (Hash[String, untyped]? value) -> Money?
    end
  end
end
