module Peddler
  module Types
    module SalesV1
      class Error < Data
        def self.new: (code: String?, message: String?, ?details: String?) -> Peddler::Types::SalesV1::Error
                    | (String?, String?, String?) -> Peddler::Types::SalesV1::Error

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::SalesV1::Error

        attr_reader code: String?

        attr_reader details: String?
        attr_reader message: String?

        def to_h: () -> { code: String?, message: String?, details: String? }
      end

      class ErrorList < Array[Error]
        def self.parse: (Array[untyped]) -> ErrorList
      end

      class GetOrderMetricsResponse < Data
        def self.new: (?errors: Array[Peddler::Types::SalesV1::Error]?, ?payload: Array[Peddler::Types::SalesV1::OrderMetricsInterval]?) -> Peddler::Types::SalesV1::GetOrderMetricsResponse
                    | (Array[Peddler::Types::SalesV1::Error]?, Array[Peddler::Types::SalesV1::OrderMetricsInterval]?) -> Peddler::Types::SalesV1::GetOrderMetricsResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::SalesV1::GetOrderMetricsResponse

        attr_reader errors: Array[Peddler::Types::SalesV1::Error]?
        attr_reader payload: Array[Peddler::Types::SalesV1::OrderMetricsInterval]?

        def to_h: () -> { errors: Array[Peddler::Types::SalesV1::Error]?, payload: Array[Peddler::Types::SalesV1::OrderMetricsInterval]? }
      end

      class OrderMetricsInterval < Data
        def self.new: (average_unit_price: Peddler::Types::Money?, interval: String?, order_count: Integer?, order_item_count: Integer?, total_sales: Peddler::Types::Money?, unit_count: Integer?) -> Peddler::Types::SalesV1::OrderMetricsInterval
                    | (Peddler::Types::Money?, String?, Integer?, Integer?, Peddler::Types::Money?, Integer?) -> Peddler::Types::SalesV1::OrderMetricsInterval

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::SalesV1::OrderMetricsInterval

        attr_reader average_unit_price: Peddler::Types::Money?
        attr_reader interval: String?
        attr_reader order_count: Integer?
        attr_reader order_item_count: Integer?
        attr_reader total_sales: Peddler::Types::Money?
        attr_reader unit_count: Integer?

        def to_h: () -> { average_unit_price: Peddler::Types::Money?, interval: String?, order_count: Integer?, order_item_count: Integer?, total_sales: Peddler::Types::Money?, unit_count: Integer? }
      end

      class OrderMetricsList < Array[OrderMetricsInterval]
        def self.parse: (Array[untyped]) -> OrderMetricsList
      end
    end
  end
end
