module Peddler
  module Types
    module Invoices20240619
      class ExportInvoicesResponse < Data
        def self.new: (?export_id: String?) -> Peddler::Types::Invoices20240619::ExportInvoicesResponse
                    | (String?) -> Peddler::Types::Invoices20240619::ExportInvoicesResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::Invoices20240619::ExportInvoicesResponse

        attr_reader export_id: String?

        def to_h: () -> { export_id: String? }
      end
    end
  end
end
