module Peddler
  module Types
    module Invoices20240619
      class GetInvoicesExportResponse < Data
        def self.new: (?export: Peddler::Types::Invoices20240619::Export?) -> Peddler::Types::Invoices20240619::GetInvoicesExportResponse
                    | (Peddler::Types::Invoices20240619::Export?) -> Peddler::Types::Invoices20240619::GetInvoicesExportResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::Invoices20240619::GetInvoicesExportResponse

        attr_reader export: Peddler::Types::Invoices20240619::Export?

        def to_h: () -> { export: Peddler::Types::Invoices20240619::Export? }
      end
    end
  end
end
