module Peddler
  module Types
    module Invoices20240619
      class TransactionIdentifier < Data
        def self.new: (?id: String?, ?name: String?) -> Peddler::Types::Invoices20240619::TransactionIdentifier
                    | (String?, String?) -> Peddler::Types::Invoices20240619::TransactionIdentifier

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::Invoices20240619::TransactionIdentifier

        attr_reader id: String?
        attr_reader name: String?

        def to_h: () -> { id: String?, name: String? }
      end
    end
  end
end
