module Peddler
  class API
    class CannotSandbox < StandardError
    end

    class MustSandbox < StandardError
    end

    @access_token: String
    @endpoint: Endpoint
    @http: HTTP::Client
    @retries: Integer
    @sandbox: bool

    attr_reader access_token: String
    attr_reader endpoint: Endpoint
    attr_reader retries: Integer

    def initialize: (String aws_region, String access_token, ?retries: Integer, ?http: HTTP::Client) -> void

    def endpoint_uri: () -> URI::HTTPS
    def sandbox: () -> self
    def sandbox?: () -> bool
    def http: (?rate_limit: Float?) -> HTTP::Client

    private

    def get: (String path, ?rate_limit: Float?, ?parser: untyped, **untyped) -> Response
    def post: (String path, ?rate_limit: Float?, ?parser: untyped, **untyped) -> Response
    def put: (String path, ?rate_limit: Float?, ?parser: untyped, **untyped) -> Response
    def delete: (String path, ?rate_limit: Float?, ?parser: untyped, **untyped) -> Response
    def patch: (String path, ?rate_limit: Float?, ?parser: untyped, **untyped) -> Response
    def request: (Symbol method, String path, ?rate_limit: Float?, ?parser: untyped, **untyped) -> Response
    def cannot_sandbox!: () -> void
    def must_sandbox!: () -> void
    def user_agent: () -> String
    def timestamp: () -> String
    def percent_encode: (String component) -> String
    def stringify_array: (Array[untyped]? val) -> String?
  end
end
