module Peddler
  ENDPOINTS: Hash[String, Hash[Symbol, String]]

  class Endpoint
    attr_reader aws_region: String
    attr_reader selling_region: String
    attr_reader host: String

    def self.new: (aws_region: String, selling_region: String, host: String) -> Endpoint
                | (**String) -> Endpoint
    def self.find: (String aws_region) -> Endpoint
    def self.find_by_selling_region: (String selling_region) -> Endpoint

    def production: () -> URI::HTTPS
    def sandbox: () -> URI::HTTPS
  end
end
