# frozen_string_literal: true

# This file is generated. Do not edit.

require "structure"

module Peddler
  module APIs
    class Tracking20260130
      # The identifier to track a shipment.
      TrackingIdentifier = Structure.new do
        # @return [String] The Air Cargo Shipment Identification Number.
        attribute?(:acsin, String)

        # @return [String] The Amazon Fulfillment Tracking Number.
        attribute?(:aftn, String)

        # @return [CarrierTracking] The carrier-assigned tracking information.
        attribute?(:carrier_tracking, CarrierTracking, from: "carrierTracking")

        # @return [String] The container number provided by the Logistics Service Provider.
        attribute?(:container_number, String, from: "containerNumber")

        # @return [String] The House Bill of Lading (HBL) number.
        attribute?(:house_bill_of_lading_number, String, from: "houseBillOfLadingNumber")

        # @return [String] A unique identifier generated by Amazon for the shipment tracking request.
        attribute?(:id, String)
      end
    end
  end
end
