module Peddler
  module Types
    module ListingsRestrictions20210801
      class Error < Data
        def self.new: (code: String?, message: String?, ?details: String?) -> Peddler::Types::ListingsRestrictions20210801::Error
                    | (String?, String?, String?) -> Peddler::Types::ListingsRestrictions20210801::Error

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ListingsRestrictions20210801::Error

        attr_reader code: String?

        attr_reader details: String?
        attr_reader message: String?

        def to_h: () -> { code: String?, message: String?, details: String? }
      end
    end
  end
end
