module Peddler
  module Types
    module ListingsRestrictions20210801
      class Link < Data
        def self.new: (resource: String?, verb: String?, ?title: String?, ?type: String?) -> Peddler::Types::ListingsRestrictions20210801::Link
                    | (String?, String?, String?, String?) -> Peddler::Types::ListingsRestrictions20210801::Link

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ListingsRestrictions20210801::Link

        attr_reader resource: String?

        attr_reader title: String?
        attr_reader type: String?
        attr_reader verb: String?

        def to_h: () -> { resource: String?, verb: String?, title: String?, type: String? }
      end
    end
  end
end
