module Peddler
  module Types
    module SupplySources20200701
      class ErrorList < Data
        def self.new: (errors: Array[Peddler::Types::SupplySources20200701::Error]?) -> Peddler::Types::SupplySources20200701::ErrorList
                    | (Array[Peddler::Types::SupplySources20200701::Error]?) -> Peddler::Types::SupplySources20200701::ErrorList

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::SupplySources20200701::ErrorList

        attr_reader errors: Array[Peddler::Types::SupplySources20200701::Error]?

        def to_h: () -> { errors: Array[Peddler::Types::SupplySources20200701::Error]? }
      end
    end
  end
end
