module Peddler
  module Types
    module SupplySources20200701
      class OperatingHoursByDay < Data
        attr_reader monday: Array[OperatingHour]?
        attr_reader tuesday: Array[OperatingHour]?
        attr_reader wednesday: Array[OperatingHour]?
        attr_reader thursday: Array[OperatingHour]?
        attr_reader friday: Array[OperatingHour]?
        attr_reader saturday: Array[OperatingHour]?
        attr_reader sunday: Array[OperatingHour]?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?monday: Array[OperatingHour],
          ?tuesday: Array[OperatingHour],
          ?wednesday: Array[OperatingHour],
          ?thursday: Array[OperatingHour],
          ?friday: Array[OperatingHour],
          ?saturday: Array[OperatingHour],
          ?sunday: Array[OperatingHour]
        ) -> void
      end
    end
  end
end
