module Peddler
  module Types
    module CatalogItems20220401
      class ItemContributorRole < Data
        def self.new: (value: String?, ?display_name: String?) -> Peddler::Types::CatalogItems20220401::ItemContributorRole
                    | (String?, String?) -> Peddler::Types::CatalogItems20220401::ItemContributorRole

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::CatalogItems20220401::ItemContributorRole

        attr_reader display_name: String?
        attr_reader value: String?

        def to_h: () -> { value: String?, display_name: String? }
      end
    end
  end
end
