module Peddler
  module Types
    module ProductPricing20220501
      class CompetitiveSummaryRequest < Data
        attr_reader asin: String
        attr_reader marketplace_id: String
        attr_reader included_data: Array[String]
        attr_reader lowest_priced_offers_inputs: Array[LowestPricedOffersInput]?
        attr_reader method: String
        attr_reader uri: String

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          asin: String,
          marketplace_id: String,
          included_data: Array[String],
          ?lowest_priced_offers_inputs: Array[LowestPricedOffersInput],
          method: String,
          uri: String
        ) -> void
      end
    end
  end
end
