module Peddler
  module Types
    module ProductPricing20220501
      class CompetitiveSummaryResponseBody < Data
        def self.new: (asin: String?, marketplace_id: String?, ?errors: Array[Peddler::Types::ProductPricing20220501::Error]?, ?featured_buying_options: Array[Peddler::Types::ProductPricing20220501::FeaturedBuyingOption]?, ?lowest_priced_offers: Array[Peddler::Types::ProductPricing20220501::LowestPricedOffer]?, ?reference_prices: Array[Peddler::Types::ProductPricing20220501::ReferencePrice]?) -> Peddler::Types::ProductPricing20220501::CompetitiveSummaryResponseBody
                    | (String?, String?, Array[Peddler::Types::ProductPricing20220501::Error]?, Array[Peddler::Types::ProductPricing20220501::FeaturedBuyingOption]?, Array[Peddler::Types::ProductPricing20220501::LowestPricedOffer]?, Array[Peddler::Types::ProductPricing20220501::ReferencePrice]?) -> Peddler::Types::ProductPricing20220501::CompetitiveSummaryResponseBody

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ProductPricing20220501::CompetitiveSummaryResponseBody

        attr_reader asin: String?

        attr_reader errors: Array[Peddler::Types::ProductPricing20220501::Error]?
        attr_reader featured_buying_options: Array[Peddler::Types::ProductPricing20220501::FeaturedBuyingOption]?
        attr_reader lowest_priced_offers: Array[Peddler::Types::ProductPricing20220501::LowestPricedOffer]?
        attr_reader marketplace_id: String?

        attr_reader reference_prices: Array[Peddler::Types::ProductPricing20220501::ReferencePrice]?

        def to_h: () -> { asin: String?, marketplace_id: String?, errors: Array[Peddler::Types::ProductPricing20220501::Error]?, featured_buying_options: Array[Peddler::Types::ProductPricing20220501::FeaturedBuyingOption]?, lowest_priced_offers: Array[Peddler::Types::ProductPricing20220501::LowestPricedOffer]?, reference_prices: Array[Peddler::Types::ProductPricing20220501::ReferencePrice]? }
      end
    end
  end
end
