module Peddler
  module Types
    module ProductPricing20220501
      class FeaturedOfferExpectedPriceResponseList < Array[FeaturedOfferExpectedPriceResponse]
        def self.parse: (Array[untyped] array) -> instance
      end
    end
  end
end
