module Peddler
  module Types
    module CatalogItems20201201
      class ErrorList < Data
        def self.new: (errors: Array[Peddler::Types::CatalogItems20201201::Error]?) -> Peddler::Types::CatalogItems20201201::ErrorList
                    | (Array[Peddler::Types::CatalogItems20201201::Error]?) -> Peddler::Types::CatalogItems20201201::ErrorList

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::CatalogItems20201201::ErrorList

        attr_reader errors: Array[Peddler::Types::CatalogItems20201201::Error]?

        def to_h: () -> { errors: Array[Peddler::Types::CatalogItems20201201::Error]? }
      end
    end
  end
end
