module Peddler
  module Types
    module CatalogItems20201201
      class ItemSalesRank < Data
        def self.new: (rank: Integer?, title: String?, ?link: String?) -> Peddler::Types::CatalogItems20201201::ItemSalesRank
                    | (Integer?, String?, String?) -> Peddler::Types::CatalogItems20201201::ItemSalesRank

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::CatalogItems20201201::ItemSalesRank

        attr_reader link: String?
        attr_reader rank: Integer?
        attr_reader title: String?

        def to_h: () -> { rank: Integer?, title: String?, link: String? }
      end
    end
  end
end
