module Peddler
  module Types
    module CatalogItems20201201
      class ItemSalesRanks < Array[ItemSalesRanksByMarketplace]
        def self.parse: (Array[untyped] array) -> instance
      end
    end
  end
end
