module Peddler
  module Types
    module ShippingV1
      class CreateShipmentResponse < Data
        def self.new: (?errors: Array[Peddler::Types::ShippingV1::Error]?, ?payload: Peddler::Types::ShippingV1::CreateShipmentResult?) -> Peddler::Types::ShippingV1::CreateShipmentResponse
                    | (Array[Peddler::Types::ShippingV1::Error]?, Peddler::Types::ShippingV1::CreateShipmentResult?) -> Peddler::Types::ShippingV1::CreateShipmentResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ShippingV1::CreateShipmentResponse

        attr_reader errors: Array[Peddler::Types::ShippingV1::Error]?
        attr_reader payload: Peddler::Types::ShippingV1::CreateShipmentResult?

        def to_h: () -> { errors: Array[Peddler::Types::ShippingV1::Error]?, payload: Peddler::Types::ShippingV1::CreateShipmentResult? }
      end
    end
  end
end
