module Peddler
  module Types
    module ShippingV1
      class PurchaseLabelsRequest < Data
        attr_reader rate_id: String
        attr_reader label_specification: LabelSpecification

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          rate_id: String,
          label_specification: LabelSpecification
        ) -> void
      end
    end
  end
end
