module Peddler
  module Types
    module ShippingV1
      class PurchaseShipmentRequest < Data
        attr_reader client_reference_id: String
        attr_reader ship_to: Address
        attr_reader ship_from: Address
        attr_reader ship_date: String?
        attr_reader service_type: String
        attr_reader containers: Array[Container]
        attr_reader label_specification: LabelSpecification

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          client_reference_id: String,
          ship_to: Address,
          ship_from: Address,
          ?ship_date: String,
          service_type: String,
          containers: Array[Container],
          label_specification: LabelSpecification
        ) -> void
      end
    end
  end
end
