module Peddler
  module Types
    module ShippingV1
      class TimeRange < Data
        def self.new: (?end: String?, ?start: String?) -> Peddler::Types::ShippingV1::TimeRange
                    | (String?, String?) -> Peddler::Types::ShippingV1::TimeRange

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ShippingV1::TimeRange

        attr_reader end: String?
        attr_reader start: String?

        def to_h: () -> { end: String?, start: String? }
      end
    end
  end
end
