module Peddler
  module Types
    module ListingsItems20210801
      class ItemImage < Data
        def self.new: (height: Integer?, link: String?, width: Integer?) -> Peddler::Types::ListingsItems20210801::ItemImage
                    | (Integer?, String?, Integer?) -> Peddler::Types::ListingsItems20210801::ItemImage

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ListingsItems20210801::ItemImage

        attr_reader height: Integer?
        attr_reader link: String?
        attr_reader width: Integer?

        def to_h: () -> { height: Integer?, link: String?, width: Integer? }
      end
    end
  end
end
