module Generator
  class Entrypoint
    attr_reader apis: Array[API]

    def initialize: (Array[API] apis) -> void

    def apis_with_latest_version: () -> Hash[String, API]
    def generate: () -> void

    def required_libraries: () -> Array[String]

    private

    def file_path: () -> String
    def render_template: () -> String

    def template: () -> String
  end
end
