module Peddler
  module Types
    module EasyShip20220323
      class Dimensions < Data
        def self.new: (?height: Float?, ?identifier: String?, ?length: Float?, ?unit: String?, ?width: Float?) -> Peddler::Types::EasyShip20220323::Dimensions
                    | (Float?, String?, Float?, String?, Float?) -> Peddler::Types::EasyShip20220323::Dimensions

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::EasyShip20220323::Dimensions

        attr_reader height: Float?
        attr_reader identifier: String?
        attr_reader length: Float?
        attr_reader unit: String?
        attr_reader width: Float?

        def to_h: () -> { height: Float?, identifier: String?, length: Float?, unit: String?, width: Float? }
      end
    end
  end
end
