module Peddler
  module Types
    module EasyShip20220323
      class UpdatePackageDetailsList < Array[UpdatePackageDetails]
        def self.parse: (Array[untyped]) -> UpdatePackageDetailsList
      end
    end
  end
end
