module Peddler
  module Types
    module ShipmentInvoicingV0
      class PaymentInformation < Data
        def self.new: (?acquirer_id: String?, ?authorization_code: String?, ?card_brand: String?, ?payment_method: String?, ?payment_value: Peddler::Types::Money?) -> Peddler::Types::ShipmentInvoicingV0::PaymentInformation
                    | (String?, String?, String?, String?, Peddler::Types::Money?) -> Peddler::Types::ShipmentInvoicingV0::PaymentInformation

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ShipmentInvoicingV0::PaymentInformation

        attr_reader acquirer_id: String?
        attr_reader authorization_code: String?
        attr_reader card_brand: String?
        attr_reader payment_method: String?
        attr_reader payment_value: Peddler::Types::Money?

        def to_h: () -> { acquirer_id: String?, authorization_code: String?, card_brand: String?, payment_method: String?, payment_value: Peddler::Types::Money? }
      end
    end
  end
end
