module Peddler
  module Types
    module ShipmentInvoicingV0
      class ShipmentItem < Data
        attr_reader asin: String?
        attr_reader seller_sku: String?
        attr_reader order_item_id: String?
        attr_reader title: String?
        attr_reader quantity_ordered: Float?
        attr_reader item_price: Money?
        attr_reader shipping_price: Money?
        attr_reader gift_wrap_price: Money?
        attr_reader shipping_discount: Money?
        attr_reader promotion_discount: Money?
        attr_reader serial_numbers: Array[String]?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?asin: String,
          ?seller_sku: String,
          ?order_item_id: String,
          ?title: String,
          ?quantity_ordered: Float,
          ?item_price: Money,
          ?shipping_price: Money,
          ?gift_wrap_price: Money,
          ?shipping_discount: Money,
          ?promotion_discount: Money,
          ?serial_numbers: Array[String]
        ) -> void
      end
    end
  end
end
