module Peddler
  module Types
    module ShipmentInvoicingV0
      class TaxClassificationList < Array[TaxClassification]
        def self.parse: (Array[untyped] array) -> instance
      end
    end
  end
end
