module Peddler
  module Types
    module FinancesV0
      class ChargeInstrumentList < Array[ChargeInstrument]
        def self.parse: (Array[untyped]) -> ChargeInstrumentList
      end
    end
  end
end
