module Peddler
  module Types
    module FinancesV0
      class CouponPaymentEventList < Array[CouponPaymentEvent]
        def self.parse: (Array[untyped]) -> CouponPaymentEventList
      end
    end
  end
end
