module Peddler
  module Types
    module FinancesV0
      class DebtRecoveryEvent < Data
        attr_reader debt_recovery_type: String?
        attr_reader recovery_amount: Currency?
        attr_reader over_payment_credit: Currency?
        attr_reader debt_recovery_item_list: Array[DebtRecoveryItem]?
        attr_reader charge_instrument_list: Array[ChargeInstrument]?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?debt_recovery_type: String,
          ?recovery_amount: Currency,
          ?over_payment_credit: Currency,
          ?debt_recovery_item_list: Array[DebtRecoveryItem],
          ?charge_instrument_list: Array[ChargeInstrument]
        ) -> void
      end
    end
  end
end
