module Peddler
  module Types
    module FinancesV0
      class FailedAdhocDisbursementEvent < Data
        attr_reader funds_transfers_type: String?
        attr_reader transfer_id: String?
        attr_reader disbursement_id: String?
        attr_reader payment_disbursement_type: String?
        attr_reader status: String?
        attr_reader transfer_amount: Currency?
        attr_reader posted_date: String?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?funds_transfers_type: String,
          ?transfer_id: String,
          ?disbursement_id: String,
          ?payment_disbursement_type: String,
          ?status: String,
          ?transfer_amount: Currency,
          ?posted_date: String
        ) -> void
      end
    end
  end
end
