module Peddler
  module Types
    module FinancesV0
      class FBALiquidationEvent < Data
        def self.new: (?liquidation_fee_amount: Peddler::Types::Money?, ?liquidation_proceeds_amount: Peddler::Types::Money?, ?original_removal_order_id: String?, ?posted_date: String?) -> Peddler::Types::FinancesV0::FBALiquidationEvent
                    | (Peddler::Types::Money?, Peddler::Types::Money?, String?, String?) -> Peddler::Types::FinancesV0::FBALiquidationEvent

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::FinancesV0::FBALiquidationEvent

        attr_reader liquidation_fee_amount: Peddler::Types::Money?
        attr_reader liquidation_proceeds_amount: Peddler::Types::Money?
        attr_reader original_removal_order_id: String?
        attr_reader posted_date: String?

        def to_h: () -> { liquidation_fee_amount: Peddler::Types::Money?, liquidation_proceeds_amount: Peddler::Types::Money?, original_removal_order_id: String?, posted_date: String? }
      end
    end
  end
end
