module Peddler
  module Types
    module FinancesV0
      class ListFinancialEventGroupsResponse < Data
        attr_reader payload: ListFinancialEventGroupsPayload?
        attr_reader errors: Array[Error]?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?payload: ListFinancialEventGroupsPayload,
          ?errors: Array[Error]
        ) -> void
      end
    end
  end
end
