module Peddler
  module Types
    module FinancesV0
      class Promotion < Data
        def self.new: (?promotion_amount: Peddler::Types::Money?, ?promotion_id: String?, ?promotion_type: String?) -> Peddler::Types::FinancesV0::Promotion
                    | (Peddler::Types::Money?, String?, String?) -> Peddler::Types::FinancesV0::Promotion

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::FinancesV0::Promotion

        attr_reader promotion_amount: Peddler::Types::Money?
        attr_reader promotion_id: String?
        attr_reader promotion_type: String?

        def to_h: () -> { promotion_amount: Peddler::Types::Money?, promotion_id: String?, promotion_type: String? }
      end
    end
  end
end
