module Peddler
  module Types
    module FinancesV0
      class RemovalShipmentAdjustmentEventList < Array[RemovalShipmentAdjustmentEvent]
        def self.parse: (Array[untyped] array) -> instance
      end
    end
  end
end
