module Peddler
  module Types
    module FinancesV0
      class RentalTransactionEventList < Array[RentalTransactionEvent]
        def self.parse: (Array[untyped]) -> RentalTransactionEventList
      end
    end
  end
end
