module Peddler
  module Types
    module FinancesV0
      class SellerDealPaymentEventList < Array[SellerDealPaymentEvent]
        def self.parse: (Array[untyped]) -> SellerDealPaymentEventList
      end
    end
  end
end
