module Peddler
  module Types
    module FinancesV0
      class SolutionProviderCreditEvent < Data
        attr_reader provider_transaction_type: String?
        attr_reader seller_order_id: String?
        attr_reader marketplace_id: String?
        attr_reader marketplace_country_code: String?
        attr_reader seller_id: String?
        attr_reader seller_store_name: String?
        attr_reader provider_id: String?
        attr_reader provider_store_name: String?
        attr_reader transaction_amount: Currency?
        attr_reader transaction_creation_date: String?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?provider_transaction_type: String,
          ?seller_order_id: String,
          ?marketplace_id: String,
          ?marketplace_country_code: String,
          ?seller_id: String,
          ?seller_store_name: String,
          ?provider_id: String,
          ?provider_store_name: String,
          ?transaction_amount: Currency,
          ?transaction_creation_date: String
        ) -> void
      end
    end
  end
end
