module Peddler
  module Types
    module FinancesV0
      class TaxWithheldComponentList < Array[TaxWithheldComponent]
        def self.parse: (Array[untyped]) -> TaxWithheldComponentList
      end
    end
  end
end
