module Peddler
  module Types
    module FinancesV0
      class TaxWithheldComponent < Data
        attr_reader tax_collection_model: String?
        attr_reader taxes_withheld: Array[ChargeComponent]?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?tax_collection_model: String,
          ?taxes_withheld: Array[ChargeComponent]
        ) -> void
      end
    end
  end
end
