module Peddler
  module Types
    module MerchantFulfillmentV0
      class AdditionalSellerInputsList < Array[AdditionalSellerInputs]
        def self.parse: (Array[untyped]) -> AdditionalSellerInputsList
      end
    end
  end
end
