module Peddler
  module Types
    module MerchantFulfillmentV0
      class AvailableDeliveryExperienceOptionsList < Array[AvailableDeliveryExperienceOption]
        def self.parse: (Array[untyped] array) -> instance
      end
    end
  end
end
