module Peddler
  module Types
    module MerchantFulfillmentV0
      class Constraint < Data
        attr_reader validation_reg_ex: String?
        attr_reader validation_string: String

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?validation_reg_ex: String,
          validation_string: String
        ) -> void
      end
    end
  end
end
