module Peddler
  module Types
    module MerchantFulfillmentV0
      class GetAdditionalSellerInputsResponse < Data
        def self.new: (?errors: Array[Peddler::Types::MerchantFulfillmentV0::Error]?, ?payload: Peddler::Types::MerchantFulfillmentV0::GetAdditionalSellerInputsResult?) -> Peddler::Types::MerchantFulfillmentV0::GetAdditionalSellerInputsResponse
                    | (Array[Peddler::Types::MerchantFulfillmentV0::Error]?, Peddler::Types::MerchantFulfillmentV0::GetAdditionalSellerInputsResult?) -> Peddler::Types::MerchantFulfillmentV0::GetAdditionalSellerInputsResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::MerchantFulfillmentV0::GetAdditionalSellerInputsResponse

        attr_reader errors: Array[Peddler::Types::MerchantFulfillmentV0::Error]?
        attr_reader payload: Peddler::Types::MerchantFulfillmentV0::GetAdditionalSellerInputsResult?

        def to_h: () -> { errors: Array[Peddler::Types::MerchantFulfillmentV0::Error]?, payload: Peddler::Types::MerchantFulfillmentV0::GetAdditionalSellerInputsResult? }
      end
    end
  end
end
