module Peddler
  module Types
    module MerchantFulfillmentV0
      class Label < Data
        attr_reader custom_text_for_label: String?
        attr_reader dimensions: LabelDimensions
        attr_reader file_contents: FileContents
        attr_reader label_format: String?
        attr_reader standard_id_for_label: String?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?custom_text_for_label: String,
          dimensions: LabelDimensions,
          file_contents: FileContents,
          ?label_format: String,
          ?standard_id_for_label: String
        ) -> void
      end
    end
  end
end
