module Peddler
  module Types
    module MerchantFulfillmentV0
      class LabelCustomization < Data
        attr_reader custom_text_for_label: String?
        attr_reader standard_id_for_label: String?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?custom_text_for_label: String,
          ?standard_id_for_label: String
        ) -> void
      end
    end
  end
end
