module Peddler
  module Types
    module MerchantFulfillmentV0
      class PackageDimensions < Data
        attr_reader length: Float?
        attr_reader width: Float?
        attr_reader height: Float?
        attr_reader unit: String?
        attr_reader predefined_package_dimensions: String?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?length: Float,
          ?width: Float,
          ?height: Float,
          ?unit: String,
          ?predefined_package_dimensions: String
        ) -> void
      end
    end
  end
end
