module Peddler
  module Types
    module MerchantFulfillmentV0
      class SellerInputDefinition < Data
        attr_reader required: bool
        attr_reader data_type: String
        attr_reader constraints: Array[Constraint]
        attr_reader input_display_text: String
        attr_reader input_target: String?
        attr_reader stored_value: AdditionalSellerInput
        attr_reader restricted_set_values: Array[String]?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          required: bool,
          data_type: String,
          constraints: Array[Constraint],
          input_display_text: String,
          ?input_target: String,
          stored_value: AdditionalSellerInput,
          ?restricted_set_values: Array[String]
        ) -> void
      end
    end
  end
end
