# frozen_string_literal: true

# This file is generated. Do not edit.

require "peddler/types/external_fulfillment_inventory_2024_09_11/actionable_error"
require "peddler/types/external_fulfillment_inventory_2024_09_11/batch_inventory_request"
require "peddler/types/external_fulfillment_inventory_2024_09_11/batch_inventory_response"
require "peddler/types/external_fulfillment_inventory_2024_09_11/error"
require "peddler/types/external_fulfillment_inventory_2024_09_11/error_list"
require "peddler/types/external_fulfillment_inventory_2024_09_11/http_status_line"
require "peddler/types/external_fulfillment_inventory_2024_09_11/inventory_request"
require "peddler/types/external_fulfillment_inventory_2024_09_11/inventory_request_params"
require "peddler/types/external_fulfillment_inventory_2024_09_11/inventory_response"
require "peddler/types/external_fulfillment_inventory_2024_09_11/inventory_response_body"
require "peddler/types/external_fulfillment_inventory_2024_09_11/marketplace_attributes"
