# frozen_string_literal: true

# This file is generated. Do not edit.

require "peddler/types/fulfillment_inbound_v0/asin_prep_instructions"
require "peddler/types/fulfillment_inbound_v0/address"
require "peddler/types/fulfillment_inbound_v0/amazon_prep_fees_details"
require "peddler/types/fulfillment_inbound_v0/amount"
require "peddler/types/fulfillment_inbound_v0/bill_of_lading_download_url"
require "peddler/types/fulfillment_inbound_v0/box_contents_fee_details"
require "peddler/types/fulfillment_inbound_v0/error"
require "peddler/types/fulfillment_inbound_v0/get_bill_of_lading_response"
require "peddler/types/fulfillment_inbound_v0/get_labels_response"
require "peddler/types/fulfillment_inbound_v0/get_prep_instructions_response"
require "peddler/types/fulfillment_inbound_v0/get_prep_instructions_result"
require "peddler/types/fulfillment_inbound_v0/get_shipment_items_response"
require "peddler/types/fulfillment_inbound_v0/get_shipment_items_result"
require "peddler/types/fulfillment_inbound_v0/get_shipments_response"
require "peddler/types/fulfillment_inbound_v0/get_shipments_result"
require "peddler/types/fulfillment_inbound_v0/inbound_shipment_info"
require "peddler/types/fulfillment_inbound_v0/inbound_shipment_item"
require "peddler/types/fulfillment_inbound_v0/invalid_asin"
require "peddler/types/fulfillment_inbound_v0/invalid_sku"
require "peddler/types/fulfillment_inbound_v0/label_download_url"
require "peddler/types/fulfillment_inbound_v0/prep_details"
require "peddler/types/fulfillment_inbound_v0/sku_prep_instructions"
