# frozen_string_literal: true

# This file is generated. Do not edit.

require "peddler/types/merchant_fulfillment_v0/additional_inputs"
require "peddler/types/merchant_fulfillment_v0/additional_seller_input"
require "peddler/types/merchant_fulfillment_v0/additional_seller_inputs"
require "peddler/types/merchant_fulfillment_v0/address"
require "peddler/types/merchant_fulfillment_v0/available_carrier_will_pick_up_option"
require "peddler/types/merchant_fulfillment_v0/available_delivery_experience_option"
require "peddler/types/merchant_fulfillment_v0/available_shipping_service_options"
require "peddler/types/merchant_fulfillment_v0/benefits"
require "peddler/types/merchant_fulfillment_v0/cancel_shipment_response"
require "peddler/types/merchant_fulfillment_v0/constraint"
require "peddler/types/merchant_fulfillment_v0/create_shipment_request"
require "peddler/types/merchant_fulfillment_v0/create_shipment_response"
require "peddler/types/merchant_fulfillment_v0/dangerous_goods_details"
require "peddler/types/merchant_fulfillment_v0/error"
require "peddler/types/merchant_fulfillment_v0/excluded_benefit"
require "peddler/types/merchant_fulfillment_v0/file_contents"
require "peddler/types/merchant_fulfillment_v0/get_additional_seller_inputs_request"
require "peddler/types/merchant_fulfillment_v0/get_additional_seller_inputs_response"
require "peddler/types/merchant_fulfillment_v0/get_additional_seller_inputs_result"
require "peddler/types/merchant_fulfillment_v0/get_eligible_shipment_services_request"
require "peddler/types/merchant_fulfillment_v0/get_eligible_shipment_services_response"
require "peddler/types/merchant_fulfillment_v0/get_eligible_shipment_services_result"
require "peddler/types/merchant_fulfillment_v0/get_shipment_response"
require "peddler/types/merchant_fulfillment_v0/item"
require "peddler/types/merchant_fulfillment_v0/item_level_fields"
require "peddler/types/merchant_fulfillment_v0/label"
require "peddler/types/merchant_fulfillment_v0/label_customization"
require "peddler/types/merchant_fulfillment_v0/label_dimensions"
require "peddler/types/merchant_fulfillment_v0/label_format_option"
require "peddler/types/merchant_fulfillment_v0/label_format_option_request"
require "peddler/types/merchant_fulfillment_v0/length"
require "peddler/types/merchant_fulfillment_v0/liquid_volume"
require "peddler/types/merchant_fulfillment_v0/package_dimensions"
require "peddler/types/merchant_fulfillment_v0/rejected_shipping_service"
require "peddler/types/merchant_fulfillment_v0/seller_input_definition"
require "peddler/types/merchant_fulfillment_v0/shipment"
require "peddler/types/merchant_fulfillment_v0/shipment_request_details"
require "peddler/types/merchant_fulfillment_v0/shipping_offering_filter"
require "peddler/types/merchant_fulfillment_v0/shipping_service"
require "peddler/types/merchant_fulfillment_v0/shipping_service_options"
require "peddler/types/merchant_fulfillment_v0/temporarily_unavailable_carrier"
require "peddler/types/merchant_fulfillment_v0/terms_and_conditions_not_accepted_carrier"
require "peddler/types/merchant_fulfillment_v0/weight"
