# frozen_string_literal: true

# This file is generated. Edit template if necessary.

require "peddler/types/notifications_v1/aggregation_filter"
require "peddler/types/notifications_v1/aggregation_settings"
require "peddler/types/notifications_v1/create_destination_request"
require "peddler/types/notifications_v1/create_destination_response"
require "peddler/types/notifications_v1/create_subscription_request"
require "peddler/types/notifications_v1/create_subscription_response"
require "peddler/types/notifications_v1/delete_destination_response"
require "peddler/types/notifications_v1/delete_subscription_by_id_response"
require "peddler/types/notifications_v1/destination"
require "peddler/types/notifications_v1/destination_resource"
require "peddler/types/notifications_v1/destination_resource_specification"
require "peddler/types/notifications_v1/error"
require "peddler/types/notifications_v1/event_bridge_resource"
require "peddler/types/notifications_v1/event_bridge_resource_specification"
require "peddler/types/notifications_v1/get_destination_response"
require "peddler/types/notifications_v1/get_destinations_response"
require "peddler/types/notifications_v1/get_subscription_by_id_response"
require "peddler/types/notifications_v1/get_subscription_response"
require "peddler/types/notifications_v1/marketplace_filter"
require "peddler/types/notifications_v1/order_change_type_filter"
require "peddler/types/notifications_v1/processing_directive"
require "peddler/types/notifications_v1/sqs_resource"
require "peddler/types/notifications_v1/subscription"
