# frozen_string_literal: true

# This file is generated. Edit template if necessary.

require "peddler/types/shipping_v1/accepted_rate"
require "peddler/types/shipping_v1/account"
require "peddler/types/shipping_v1/address"
require "peddler/types/shipping_v1/cancel_shipment_response"
require "peddler/types/shipping_v1/container"
require "peddler/types/shipping_v1/container_item"
require "peddler/types/shipping_v1/container_specification"
require "peddler/types/shipping_v1/create_shipment_request"
require "peddler/types/shipping_v1/create_shipment_response"
require "peddler/types/shipping_v1/create_shipment_result"
require "peddler/types/shipping_v1/currency"
require "peddler/types/shipping_v1/dimensions"
require "peddler/types/shipping_v1/error"
require "peddler/types/shipping_v1/event"
require "peddler/types/shipping_v1/get_account_response"
require "peddler/types/shipping_v1/get_rates_request"
require "peddler/types/shipping_v1/get_rates_response"
require "peddler/types/shipping_v1/get_rates_result"
require "peddler/types/shipping_v1/get_shipment_response"
require "peddler/types/shipping_v1/get_tracking_information_response"
require "peddler/types/shipping_v1/label"
require "peddler/types/shipping_v1/label_result"
require "peddler/types/shipping_v1/label_specification"
require "peddler/types/shipping_v1/location"
require "peddler/types/shipping_v1/party"
require "peddler/types/shipping_v1/purchase_labels_request"
require "peddler/types/shipping_v1/purchase_labels_response"
require "peddler/types/shipping_v1/purchase_labels_result"
require "peddler/types/shipping_v1/purchase_shipment_request"
require "peddler/types/shipping_v1/purchase_shipment_response"
require "peddler/types/shipping_v1/purchase_shipment_result"
require "peddler/types/shipping_v1/rate"
require "peddler/types/shipping_v1/retrieve_shipping_label_request"
require "peddler/types/shipping_v1/retrieve_shipping_label_response"
require "peddler/types/shipping_v1/retrieve_shipping_label_result"
require "peddler/types/shipping_v1/service_rate"
require "peddler/types/shipping_v1/shipment"
require "peddler/types/shipping_v1/shipping_promise_set"
require "peddler/types/shipping_v1/time_range"
require "peddler/types/shipping_v1/tracking_information"
require "peddler/types/shipping_v1/tracking_summary"
require "peddler/types/shipping_v1/weight"
