# frozen_string_literal: true

# This file is generated. Do not edit.

require "peddler/types/vendor_orders_v1/acknowledgement_status_details"
require "peddler/types/vendor_orders_v1/address"
require "peddler/types/vendor_orders_v1/error"
require "peddler/types/vendor_orders_v1/get_purchase_order_response"
require "peddler/types/vendor_orders_v1/get_purchase_orders_response"
require "peddler/types/vendor_orders_v1/get_purchase_orders_status_response"
require "peddler/types/vendor_orders_v1/import_details"
require "peddler/types/vendor_orders_v1/item_quantity"
require "peddler/types/vendor_orders_v1/order"
require "peddler/types/vendor_orders_v1/order_acknowledgement"
require "peddler/types/vendor_orders_v1/order_acknowledgement_item"
require "peddler/types/vendor_orders_v1/order_details"
require "peddler/types/vendor_orders_v1/order_item"
require "peddler/types/vendor_orders_v1/order_item_acknowledgement"
require "peddler/types/vendor_orders_v1/order_item_status"
require "peddler/types/vendor_orders_v1/order_list"
require "peddler/types/vendor_orders_v1/order_list_status"
require "peddler/types/vendor_orders_v1/order_status"
require "peddler/types/vendor_orders_v1/ordered_quantity_details"
require "peddler/types/vendor_orders_v1/pagination"
require "peddler/types/vendor_orders_v1/party_identification"
require "peddler/types/vendor_orders_v1/submit_acknowledgement_request"
require "peddler/types/vendor_orders_v1/submit_acknowledgement_response"
require "peddler/types/vendor_orders_v1/tax_registration_details"
require "peddler/types/vendor_orders_v1/transaction_id"
