# frozen_string_literal: true

require "peddler/types/vendor_direct_fulfillment_sandbox_test_data_2021_10_28/error"
require "peddler/types/vendor_direct_fulfillment_sandbox_test_data_2021_10_28/error_list"
require "peddler/types/vendor_direct_fulfillment_sandbox_test_data_2021_10_28/generate_order_scenario_request"
require "peddler/types/vendor_direct_fulfillment_sandbox_test_data_2021_10_28/order_scenario_request"
require "peddler/types/vendor_direct_fulfillment_sandbox_test_data_2021_10_28/pagination"
require "peddler/types/vendor_direct_fulfillment_sandbox_test_data_2021_10_28/party_identification"
require "peddler/types/vendor_direct_fulfillment_sandbox_test_data_2021_10_28/scenario"
require "peddler/types/vendor_direct_fulfillment_sandbox_test_data_2021_10_28/test_case_data"
require "peddler/types/vendor_direct_fulfillment_sandbox_test_data_2021_10_28/test_order"
require "peddler/types/vendor_direct_fulfillment_sandbox_test_data_2021_10_28/transaction"
require "peddler/types/vendor_direct_fulfillment_sandbox_test_data_2021_10_28/transaction_reference"
require "peddler/types/vendor_direct_fulfillment_sandbox_test_data_2021_10_28/transaction_status"
