# frozen_string_literal: true

# This file is generated. Edit template if necessary.

require "peddler/types/vendor_direct_fulfillment_payments_v1/additional_details"
require "peddler/types/vendor_direct_fulfillment_payments_v1/address"
require "peddler/types/vendor_direct_fulfillment_payments_v1/charge_details"
require "peddler/types/vendor_direct_fulfillment_payments_v1/error"
require "peddler/types/vendor_direct_fulfillment_payments_v1/invoice_detail"
require "peddler/types/vendor_direct_fulfillment_payments_v1/invoice_item"
require "peddler/types/vendor_direct_fulfillment_payments_v1/item_quantity"
require "peddler/types/vendor_direct_fulfillment_payments_v1/party_identification"
require "peddler/types/vendor_direct_fulfillment_payments_v1/submit_invoice_request"
require "peddler/types/vendor_direct_fulfillment_payments_v1/submit_invoice_response"
require "peddler/types/vendor_direct_fulfillment_payments_v1/tax_detail"
require "peddler/types/vendor_direct_fulfillment_payments_v1/tax_registration_detail"
require "peddler/types/vendor_direct_fulfillment_payments_v1/transaction_reference"
