# frozen_string_literal: true

require "peddler/types/vendor_invoices_v1/additional_details"
require "peddler/types/vendor_invoices_v1/address"
require "peddler/types/vendor_invoices_v1/allowance_details"
require "peddler/types/vendor_invoices_v1/charge_details"
require "peddler/types/vendor_invoices_v1/credit_note_details"
require "peddler/types/vendor_invoices_v1/error"
require "peddler/types/vendor_invoices_v1/invoice"
require "peddler/types/vendor_invoices_v1/invoice_item"
require "peddler/types/vendor_invoices_v1/item_quantity"
require "peddler/types/vendor_invoices_v1/party_identification"
require "peddler/types/vendor_invoices_v1/payment_terms"
require "peddler/types/vendor_invoices_v1/submit_invoices_request"
require "peddler/types/vendor_invoices_v1/submit_invoices_response"
require "peddler/types/vendor_invoices_v1/tax_details"
require "peddler/types/vendor_invoices_v1/tax_registration_details"
require "peddler/types/vendor_invoices_v1/total_weight"
require "peddler/types/vendor_invoices_v1/transaction_id"
