module Peddler
  module Types
    module FulfillmentInbound20240320
      class ConfirmPlacementOptionResponse < Data
        def self.new: (operation_id: String?) -> Peddler::Types::FulfillmentInbound20240320::ConfirmPlacementOptionResponse
                    | (String?) -> Peddler::Types::FulfillmentInbound20240320::ConfirmPlacementOptionResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::FulfillmentInbound20240320::ConfirmPlacementOptionResponse

        attr_reader operation_id: String?

        def to_h: () -> { operation_id: String? }
      end
    end
  end
end
