module Peddler
  module Types
    module FulfillmentInbound20240320
      class ConfirmTransportationOptionsRequest < Data
        def self.new: (transportation_selections: Array[Peddler::Types::FulfillmentInbound20240320::TransportationSelection]?) -> Peddler::Types::FulfillmentInbound20240320::ConfirmTransportationOptionsRequest
                    | (Array[Peddler::Types::FulfillmentInbound20240320::TransportationSelection]?) -> Peddler::Types::FulfillmentInbound20240320::ConfirmTransportationOptionsRequest

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::FulfillmentInbound20240320::ConfirmTransportationOptionsRequest

        attr_reader transportation_selections: Array[Peddler::Types::FulfillmentInbound20240320::TransportationSelection]?

        def to_h: () -> { transportation_selections: Array[Peddler::Types::FulfillmentInbound20240320::TransportationSelection]? }
      end
    end
  end
end
