module Peddler
  module Types
    module FulfillmentInbound20240320
      class LtlTrackingDetailInput < Data
        def self.new: (freight_bill_number: Array[String]?, ?bill_of_lading_number: String?) -> Peddler::Types::FulfillmentInbound20240320::LtlTrackingDetailInput
                    | (Array[String]?, String?) -> Peddler::Types::FulfillmentInbound20240320::LtlTrackingDetailInput

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::FulfillmentInbound20240320::LtlTrackingDetailInput

        attr_reader bill_of_lading_number: String?
        attr_reader freight_bill_number: Array[String]?

        def to_h: () -> { freight_bill_number: Array[String]?, bill_of_lading_number: String? }
      end
    end
  end
end
