module Peddler
  module Types
    module ProductFeesV0
      class FeesEstimateRequest < Data
        attr_reader marketplace_id: String
        attr_reader amazon_fulfilled: bool?
        attr_reader price_to_estimate_fees: PriceToEstimateFees
        attr_reader identifier: String
        attr_reader optional_fulfillment_program: String?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          marketplace_id: String,
          ?amazon_fulfilled: bool,
          price_to_estimate_fees: PriceToEstimateFees,
          identifier: String,
          ?optional_fulfillment_program: String
        ) -> void
      end
    end
  end
end
