module Peddler
  module Types
    module ProductFeesV0
      class FeesEstimateRequest < Data
        def self.new: (identifier: String?, marketplace_id: String?, price_to_estimate_fees: Peddler::Types::ProductFeesV0::PriceToEstimateFees?, ?amazon_fulfilled: bool?, ?optional_fulfillment_program: String?) -> Peddler::Types::ProductFeesV0::FeesEstimateRequest
                    | (String?, String?, Peddler::Types::ProductFeesV0::PriceToEstimateFees?, bool?, String?) -> Peddler::Types::ProductFeesV0::FeesEstimateRequest

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ProductFeesV0::FeesEstimateRequest

        attr_reader amazon_fulfilled: bool?
        attr_reader identifier: String?
        attr_reader marketplace_id: String?

        attr_reader optional_fulfillment_program: String?
        attr_reader price_to_estimate_fees: Peddler::Types::ProductFeesV0::PriceToEstimateFees?

        def amazon_fulfilled?: () -> bool
        def to_h: () -> { identifier: String?, marketplace_id: String?, price_to_estimate_fees: Peddler::Types::ProductFeesV0::PriceToEstimateFees?, amazon_fulfilled: bool?, optional_fulfillment_program: String? }
      end
    end
  end
end
