module Peddler
  module Types
    module ProductFeesV0
      class FeesEstimate < Data
        attr_reader time_of_fees_estimation: String
        attr_reader total_fees_estimate: Money?
        attr_reader fee_detail_list: Array[FeeDetail]?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          time_of_fees_estimation: String,
          ?total_fees_estimate: Money,
          ?fee_detail_list: Array[FeeDetail]
        ) -> void
      end
    end
  end
end
