module Peddler
  module Types
    module ProductFeesV0
      class GetMyFeesEstimatesResponse < Array[FeesEstimateResult]
        def self.parse: (Array[untyped] array) -> instance
      end
    end
  end
end
