module Peddler
  module Types
    module ProductFeesV0
      class GetMyFeesEstimatesRequest < Array[FeesEstimateByIdRequest]
        def self.parse: (Array[untyped] array) -> instance
      end
    end
  end
end
