module Peddler
  module Types
    module Finances20240619
      class PaymentsContext < Data
        def self.new: (?payment_date: String?, ?payment_method: String?, ?payment_reference: String?, ?payment_type: String?) -> Peddler::Types::Finances20240619::PaymentsContext
                    | (String?, String?, String?, String?) -> Peddler::Types::Finances20240619::PaymentsContext

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::Finances20240619::PaymentsContext

        attr_reader payment_date: String?
        attr_reader payment_method: String?
        attr_reader payment_reference: String?
        attr_reader payment_type: String?

        def to_h: () -> { payment_date: String?, payment_method: String?, payment_reference: String?, payment_type: String? }
      end
    end
  end
end
