module Peddler
  module Types
    module VendorShipmentsV1
      class PackedQuantity < Data
        def self.new: (amount: Integer?, unit_of_measure: String?, ?unit_size: Integer?) -> Peddler::Types::VendorShipmentsV1::PackedQuantity
                    | (Integer?, String?, Integer?) -> Peddler::Types::VendorShipmentsV1::PackedQuantity

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorShipmentsV1::PackedQuantity

        attr_reader amount: Integer?
        attr_reader unit_of_measure: String?
        attr_reader unit_size: Integer?

        def to_h: () -> { amount: Integer?, unit_of_measure: String?, unit_size: Integer? }
      end
    end
  end
end
