module Peddler
  module Types
    module VendorShipmentsV1
      class ShipmentStatusDetails < Data
        def self.new: (?shipment_status: String?, ?shipment_status_date: String?) -> Peddler::Types::VendorShipmentsV1::ShipmentStatusDetails
                    | (String?, String?) -> Peddler::Types::VendorShipmentsV1::ShipmentStatusDetails

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorShipmentsV1::ShipmentStatusDetails

        attr_reader shipment_status: String?
        attr_reader shipment_status_date: String?

        def to_h: () -> { shipment_status: String?, shipment_status_date: String? }
      end
    end
  end
end
