module Peddler
  module Types
    module VendorShipmentsV1
      class TransportationDetailsForShipmentConfirmation < Data
        def self.new: (?bill_of_lading_number: String?, ?carrier_scac: String?, ?carrier_shipment_reference_number: String?, ?transportation_mode: String?) -> Peddler::Types::VendorShipmentsV1::TransportationDetailsForShipmentConfirmation
                    | (String?, String?, String?, String?) -> Peddler::Types::VendorShipmentsV1::TransportationDetailsForShipmentConfirmation

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorShipmentsV1::TransportationDetailsForShipmentConfirmation

        attr_reader bill_of_lading_number: String?
        attr_reader carrier_scac: String?
        attr_reader carrier_shipment_reference_number: String?
        attr_reader transportation_mode: String?

        def to_h: () -> { bill_of_lading_number: String?, carrier_scac: String?, carrier_shipment_reference_number: String?, transportation_mode: String? }
      end
    end
  end
end
