module Peddler
  module Types
    module Feeds20210630
      class CreateFeedSpecification < Data
        def self.new: (feed_type: String?, input_feed_document_id: String?, marketplace_ids: Array[String]?, ?feed_options: Hash[untyped, untyped]?) -> Peddler::Types::Feeds20210630::CreateFeedSpecification
                    | (String?, String?, Array[String]?, Hash[untyped, untyped]?) -> Peddler::Types::Feeds20210630::CreateFeedSpecification

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::Feeds20210630::CreateFeedSpecification

        attr_reader feed_options: Hash[untyped, untyped]?
        attr_reader feed_type: String?
        attr_reader input_feed_document_id: String?
        attr_reader marketplace_ids: Array[String]?

        def to_h: () -> { feed_type: String?, input_feed_document_id: String?, marketplace_ids: Array[String]?, feed_options: Hash[untyped, untyped]? }
      end
    end
  end
end
