module Peddler
  module Types
    module Feeds20210630
      class ErrorList < Data
        def self.new: (errors: Array[Peddler::Types::Feeds20210630::Error]?) -> Peddler::Types::Feeds20210630::ErrorList
                    | (Array[Peddler::Types::Feeds20210630::Error]?) -> Peddler::Types::Feeds20210630::ErrorList

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::Feeds20210630::ErrorList

        attr_reader errors: Array[Peddler::Types::Feeds20210630::Error]?

        def to_h: () -> { errors: Array[Peddler::Types::Feeds20210630::Error]? }
      end
    end
  end
end
