module Peddler
  module Types
    module ServicesV1
      class CreateReservationRequest < Data
        def self.new: (reservation: Peddler::Types::ServicesV1::Reservation?, resource_id: String?) -> Peddler::Types::ServicesV1::CreateReservationRequest
                    | (Peddler::Types::ServicesV1::Reservation?, String?) -> Peddler::Types::ServicesV1::CreateReservationRequest

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::ServicesV1::CreateReservationRequest

        attr_reader reservation: Peddler::Types::ServicesV1::Reservation?
        attr_reader resource_id: String?

        def to_h: () -> { reservation: Peddler::Types::ServicesV1::Reservation?, resource_id: String? }
      end
    end
  end
end
