module Peddler
  module Types
    module ServicesV1
      class RangeSlot < Data
        attr_reader start_date_time: String?
        attr_reader end_date_time: String?
        attr_reader capacity: Integer?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?start_date_time: String,
          ?end_date_time: String,
          ?capacity: Integer
        ) -> void
      end
    end
  end
end
