module Peddler
  module Types
    module ServicesV1
      class Technician < Data
        attr_reader technician_id: String?
        attr_reader name: String?

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          ?technician_id: String,
          ?name: String
        ) -> void
      end
    end
  end
end
