# frozen_string_literal: true

module Generator
  module RBS
    class Entrypoint
      attr_reader apis: Array[Generator::API]

      def initialize: (Array[Generator::API] apis) -> void

      def generate: () -> void

      def api_methods: () -> Array[Hash[Symbol, String]]

      def apis_with_latest_version: () -> Hash[String, Generator::API]

      private

      def render_template: () -> String

      def file_path: () -> String

      def template: () -> String
    end
  end
end
