module Peddler
  module Types
    module VendorDirectFulfillmentOrders20211228
      class OrderList < Data
        def self.new: (?orders: Array[Peddler::Types::VendorDirectFulfillmentOrders20211228::Order]?, ?pagination: Peddler::Types::VendorDirectFulfillmentOrders20211228::Pagination?) -> Peddler::Types::VendorDirectFulfillmentOrders20211228::OrderList
                    | (Array[Peddler::Types::VendorDirectFulfillmentOrders20211228::Order]?, Peddler::Types::VendorDirectFulfillmentOrders20211228::Pagination?) -> Peddler::Types::VendorDirectFulfillmentOrders20211228::OrderList

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorDirectFulfillmentOrders20211228::OrderList

        attr_reader orders: Array[Peddler::Types::VendorDirectFulfillmentOrders20211228::Order]?
        attr_reader pagination: Peddler::Types::VendorDirectFulfillmentOrders20211228::Pagination?

        def to_h: () -> { orders: Array[Peddler::Types::VendorDirectFulfillmentOrders20211228::Order]?, pagination: Peddler::Types::VendorDirectFulfillmentOrders20211228::Pagination? }
      end
    end
  end
end
