module Peddler
  module Types
    module VendorDirectFulfillmentOrders20211228
      class ShipmentDetails < Data
        def self.new: (priority_shipment: bool?, pslip_required: bool?, message_to_customer: String?, ship_method: String?, shipment_dates: Peddler::Types::VendorDirectFulfillmentOrders20211228::ShipmentDates?, ?gift: bool?, ?scheduled_delivery_shipment: bool?) -> Peddler::Types::VendorDirectFulfillmentOrders20211228::ShipmentDetails
                    | (bool?, bool?, String?, String?, Peddler::Types::VendorDirectFulfillmentOrders20211228::ShipmentDates?, bool?, bool?) -> Peddler::Types::VendorDirectFulfillmentOrders20211228::ShipmentDetails

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::VendorDirectFulfillmentOrders20211228::ShipmentDetails

        attr_reader gift: bool?
        attr_reader message_to_customer: String?
        attr_reader priority_shipment: bool?
        attr_reader pslip_required: bool?

        attr_reader scheduled_delivery_shipment: bool?
        attr_reader ship_method: String?
        attr_reader shipment_dates: Peddler::Types::VendorDirectFulfillmentOrders20211228::ShipmentDates?

        def gift?: () -> bool
        def priority_shipment?: () -> bool
        def pslip_required?: () -> bool

        def scheduled_delivery_shipment?: () -> bool
        def to_h: () -> { priority_shipment: bool?, pslip_required: bool?, message_to_customer: String?, ship_method: String?, shipment_dates: Peddler::Types::VendorDirectFulfillmentOrders20211228::ShipmentDates?, gift: bool?, scheduled_delivery_shipment: bool? }
      end
    end
  end
end
