module Peddler
  module APIs
    class EasyShip20220323 < API
      def self.typed: () -> singleton(EasyShip20220323)

      def create_scheduled_package: (Hash[untyped, untyped], ?rate_limit: Float) -> Peddler::Response

      def create_scheduled_package_bulk: (Hash[untyped, untyped], ?rate_limit: Float) -> Peddler::Response
      def get_scheduled_package: (String, String, ?rate_limit: Float) -> Peddler::Response
      def list_handover_slots: (?list_handover_slots_request: Hash[untyped, untyped]?, ?rate_limit: Float) -> Peddler::Response

      def update_scheduled_packages: (?update_scheduled_packages_request: Hash[untyped, untyped]?, ?rate_limit: Float) -> Peddler::Response
    end
  end
end
