module Peddler
  module APIs
    class ExternalFulfillmentReturns20240911 < API
      class Error < Data
        def self.new: (code: String, message: String, ?details: String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::Error
                    | (String, String, String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::Error
        def self.[]: (code: String, message: String, ?details: String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::Error
                   | (String, String, String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::Error

        def self.members: () -> [ :code, :message, :details ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::APIs::ExternalFulfillmentReturns20240911::Error

        attr_reader code: String
        attr_reader details: String?
        attr_reader message: String

        def members: () -> [ :code, :message, :details ]
        def to_h: () -> { code: String, message: String, details: String? }
      end

      class ErrorList < Data
        def self.new: (errors: Array[Peddler::APIs::ExternalFulfillmentReturns20240911::Error]) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ErrorList
                    | (Array[Peddler::APIs::ExternalFulfillmentReturns20240911::Error]) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ErrorList
        def self.[]: (errors: Array[Peddler::APIs::ExternalFulfillmentReturns20240911::Error]) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ErrorList
                   | (Array[Peddler::APIs::ExternalFulfillmentReturns20240911::Error]) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ErrorList

        def self.members: () -> [ :errors ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ErrorList

        attr_reader errors: Array[Peddler::APIs::ExternalFulfillmentReturns20240911::Error]

        def members: () -> [ :errors ]
        def to_h: () -> { errors: Array[Peddler::APIs::ExternalFulfillmentReturns20240911::Error] }
      end

      class InvoiceInformation < Data
        def self.new: (id: String) -> Peddler::APIs::ExternalFulfillmentReturns20240911::InvoiceInformation
                    | (String) -> Peddler::APIs::ExternalFulfillmentReturns20240911::InvoiceInformation
        def self.[]: (id: String) -> Peddler::APIs::ExternalFulfillmentReturns20240911::InvoiceInformation
                   | (String) -> Peddler::APIs::ExternalFulfillmentReturns20240911::InvoiceInformation

        def self.members: () -> [ :id ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::APIs::ExternalFulfillmentReturns20240911::InvoiceInformation

        attr_reader id: String

        def members: () -> [ :id ]
        def to_h: () -> { id: String }
      end

      class MarketplaceChannel < Data
        def self.new: (?channel_name: String?, ?marketplace_name: String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannel
                    | (String?, String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannel
        def self.[]: (?channel_name: String?, ?marketplace_name: String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannel
                   | (String?, String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannel

        def self.members: () -> [ :channel_name, :marketplace_name ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannel

        attr_reader channel_name: String?
        attr_reader marketplace_name: String?

        def members: () -> [ :channel_name, :marketplace_name ]
        def to_h: () -> { channel_name: String?, marketplace_name: String? }
      end

      class MarketplaceChannelDetails < Data
        def self.new: (?channel_sku: String?, ?customer_order_id: String?, ?exchange_order_id: String?, ?marketplace_channel: Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannel?, ?merchant_id: String?, ?return_location_id: String?, ?shipment_id: String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannelDetails
                    | (String?, String?, String?, Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannel?, String?, String?, String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannelDetails
        def self.[]: (?channel_sku: String?, ?customer_order_id: String?, ?exchange_order_id: String?, ?marketplace_channel: Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannel?, ?merchant_id: String?, ?return_location_id: String?, ?shipment_id: String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannelDetails
                   | (String?, String?, String?, Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannel?, String?, String?, String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannelDetails

        def self.members: () -> [ :channel_sku, :customer_order_id, :exchange_order_id, :marketplace_channel, :merchant_id, :return_location_id, :shipment_id ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannelDetails

        attr_reader channel_sku: String?
        attr_reader customer_order_id: String?
        attr_reader exchange_order_id: String?
        attr_reader marketplace_channel: Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannel?
        attr_reader merchant_id: String?
        attr_reader return_location_id: String?
        attr_reader shipment_id: String?

        def members: () -> [ :channel_sku, :customer_order_id, :exchange_order_id, :marketplace_channel, :merchant_id, :return_location_id, :shipment_id ]
        def to_h: () -> { channel_sku: String?, customer_order_id: String?, exchange_order_id: String?, marketplace_channel: Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannel?, merchant_id: String?, return_location_id: String?, shipment_id: String? }
      end

      class OtpDetails < Data
        def self.new: (otp: String, valid_till: Integer) -> Peddler::APIs::ExternalFulfillmentReturns20240911::OtpDetails
                    | (String, Integer) -> Peddler::APIs::ExternalFulfillmentReturns20240911::OtpDetails
        def self.[]: (otp: String, valid_till: Integer) -> Peddler::APIs::ExternalFulfillmentReturns20240911::OtpDetails
                   | (String, Integer) -> Peddler::APIs::ExternalFulfillmentReturns20240911::OtpDetails

        def self.members: () -> [ :otp, :valid_till ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::APIs::ExternalFulfillmentReturns20240911::OtpDetails

        attr_reader otp: String
        attr_reader valid_till: Integer

        def members: () -> [ :otp, :valid_till ]
        def to_h: () -> { otp: String, valid_till: Integer }
      end

      class ReplanningDetails < Data
        def self.new: (?previous_tracking_info: Array[Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo]?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReplanningDetails
                    | (Array[Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo]?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReplanningDetails
        def self.[]: (?previous_tracking_info: Array[Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo]?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReplanningDetails
                   | (Array[Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo]?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReplanningDetails

        def self.members: () -> [ :previous_tracking_info ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReplanningDetails

        attr_reader previous_tracking_info: Array[Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo]?

        def members: () -> [ :previous_tracking_info ]
        def to_h: () -> { previous_tracking_info: Array[Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo]? }
      end

      class Return < Data
        def self.new: (fulfillment_location_id: String, id: String, last_updated_date_time: String, marketplace_channel_details: Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannelDetails, return_metadata: Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnMetadata, return_shipping_info: Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnShippingInfo, return_type: String, status: String, ?creation_date_time: String?, ?merchant_sku: String?, ?number_of_units: Integer?, ?otp_details: Peddler::APIs::ExternalFulfillmentReturns20240911::OtpDetails?, ?package_delivery_mode: String?, ?replanning_details: Peddler::APIs::ExternalFulfillmentReturns20240911::ReplanningDetails?, ?return_location_id: String?, ?return_sub_type: String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::Return
                    | (String, String, String, Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannelDetails, Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnMetadata, Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnShippingInfo, String, String, String?, String?, Integer?, Peddler::APIs::ExternalFulfillmentReturns20240911::OtpDetails?, String?, Peddler::APIs::ExternalFulfillmentReturns20240911::ReplanningDetails?, String?, String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::Return
        def self.[]: (fulfillment_location_id: String, id: String, last_updated_date_time: String, marketplace_channel_details: Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannelDetails, return_metadata: Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnMetadata, return_shipping_info: Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnShippingInfo, return_type: String, status: String, ?creation_date_time: String?, ?merchant_sku: String?, ?number_of_units: Integer?, ?otp_details: Peddler::APIs::ExternalFulfillmentReturns20240911::OtpDetails?, ?package_delivery_mode: String?, ?replanning_details: Peddler::APIs::ExternalFulfillmentReturns20240911::ReplanningDetails?, ?return_location_id: String?, ?return_sub_type: String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::Return
                   | (String, String, String, Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannelDetails, Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnMetadata, Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnShippingInfo, String, String, String?, String?, Integer?, Peddler::APIs::ExternalFulfillmentReturns20240911::OtpDetails?, String?, Peddler::APIs::ExternalFulfillmentReturns20240911::ReplanningDetails?, String?, String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::Return

        def self.members: () -> [ :fulfillment_location_id, :id, :last_updated_date_time, :marketplace_channel_details, :return_metadata, :return_shipping_info, :return_type, :status, :creation_date_time, :merchant_sku, :number_of_units, :otp_details, :package_delivery_mode, :replanning_details, :return_location_id, :return_sub_type ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::APIs::ExternalFulfillmentReturns20240911::Return

        attr_reader creation_date_time: String?
        attr_reader fulfillment_location_id: String
        attr_reader id: String
        attr_reader last_updated_date_time: String
        attr_reader marketplace_channel_details: Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannelDetails
        attr_reader merchant_sku: String?
        attr_reader number_of_units: Integer?
        attr_reader otp_details: Peddler::APIs::ExternalFulfillmentReturns20240911::OtpDetails?
        attr_reader package_delivery_mode: String?
        attr_reader replanning_details: Peddler::APIs::ExternalFulfillmentReturns20240911::ReplanningDetails?
        attr_reader return_location_id: String?
        attr_reader return_metadata: Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnMetadata
        attr_reader return_shipping_info: Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnShippingInfo
        attr_reader return_sub_type: String?
        attr_reader return_type: String
        attr_reader status: String

        def members: () -> [ :fulfillment_location_id, :id, :last_updated_date_time, :marketplace_channel_details, :return_metadata, :return_shipping_info, :return_type, :status, :creation_date_time, :merchant_sku, :number_of_units, :otp_details, :package_delivery_mode, :replanning_details, :return_location_id, :return_sub_type ]
        def to_h: () -> { fulfillment_location_id: String, id: String, last_updated_date_time: String, marketplace_channel_details: Peddler::APIs::ExternalFulfillmentReturns20240911::MarketplaceChannelDetails, return_metadata: Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnMetadata, return_shipping_info: Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnShippingInfo, return_type: String, status: String, creation_date_time: String?, merchant_sku: String?, number_of_units: Integer?, otp_details: Peddler::APIs::ExternalFulfillmentReturns20240911::OtpDetails?, package_delivery_mode: String?, replanning_details: Peddler::APIs::ExternalFulfillmentReturns20240911::ReplanningDetails?, return_location_id: String?, return_sub_type: String? }
      end

      class ReturnMetadata < Data
        def self.new: (return_reason: String, ?fulfillment_order_id: String?, ?invoice_information: Peddler::APIs::ExternalFulfillmentReturns20240911::InvoiceInformation?, ?rma_id: String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnMetadata
                    | (String, String?, Peddler::APIs::ExternalFulfillmentReturns20240911::InvoiceInformation?, String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnMetadata
        def self.[]: (return_reason: String, ?fulfillment_order_id: String?, ?invoice_information: Peddler::APIs::ExternalFulfillmentReturns20240911::InvoiceInformation?, ?rma_id: String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnMetadata
                   | (String, String?, Peddler::APIs::ExternalFulfillmentReturns20240911::InvoiceInformation?, String?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnMetadata

        def self.members: () -> [ :return_reason, :fulfillment_order_id, :invoice_information, :rma_id ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnMetadata

        attr_reader fulfillment_order_id: String?
        attr_reader invoice_information: Peddler::APIs::ExternalFulfillmentReturns20240911::InvoiceInformation?
        attr_reader return_reason: String
        attr_reader rma_id: String?

        def members: () -> [ :return_reason, :fulfillment_order_id, :invoice_information, :rma_id ]
        def to_h: () -> { return_reason: String, fulfillment_order_id: String?, invoice_information: Peddler::APIs::ExternalFulfillmentReturns20240911::InvoiceInformation?, rma_id: String? }
      end

      class ReturnShippingInfo < Data
        def self.new: (?delivery_date_time: String?, ?forward_tracking_info: Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo?, ?pickup_date_time: String?, ?reverse_tracking_info: Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnShippingInfo
                    | (String?, Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo?, String?, Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnShippingInfo
        def self.[]: (?delivery_date_time: String?, ?forward_tracking_info: Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo?, ?pickup_date_time: String?, ?reverse_tracking_info: Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnShippingInfo
                   | (String?, Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo?, String?, Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnShippingInfo

        def self.members: () -> [ :delivery_date_time, :forward_tracking_info, :pickup_date_time, :reverse_tracking_info ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnShippingInfo

        attr_reader delivery_date_time: String?
        attr_reader forward_tracking_info: Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo?
        attr_reader pickup_date_time: String?
        attr_reader reverse_tracking_info: Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo?

        def members: () -> [ :delivery_date_time, :forward_tracking_info, :pickup_date_time, :reverse_tracking_info ]
        def to_h: () -> { delivery_date_time: String?, forward_tracking_info: Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo?, pickup_date_time: String?, reverse_tracking_info: Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo? }
      end

      class ReturnsResponse < Data
        def self.new: (?next_token: String?, ?returns: Array[Peddler::APIs::ExternalFulfillmentReturns20240911::Return]?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnsResponse
                    | (String?, Array[Peddler::APIs::ExternalFulfillmentReturns20240911::Return]?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnsResponse
        def self.[]: (?next_token: String?, ?returns: Array[Peddler::APIs::ExternalFulfillmentReturns20240911::Return]?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnsResponse
                   | (String?, Array[Peddler::APIs::ExternalFulfillmentReturns20240911::Return]?) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnsResponse

        def self.members: () -> [ :next_token, :returns ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::APIs::ExternalFulfillmentReturns20240911::ReturnsResponse

        attr_reader next_token: String?
        attr_reader returns: Array[Peddler::APIs::ExternalFulfillmentReturns20240911::Return]?

        def members: () -> [ :next_token, :returns ]
        def to_h: () -> { next_token: String?, returns: Array[Peddler::APIs::ExternalFulfillmentReturns20240911::Return]? }
      end

      class TrackingInfo < Data
        def self.new: (carrier_name: String, tracking_id: String) -> Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo
                    | (String, String) -> Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo
        def self.[]: (carrier_name: String, tracking_id: String) -> Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo
                   | (String, String) -> Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo

        def self.members: () -> [ :carrier_name, :tracking_id ]

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::APIs::ExternalFulfillmentReturns20240911::TrackingInfo

        attr_reader carrier_name: String
        attr_reader tracking_id: String

        def members: () -> [ :carrier_name, :tracking_id ]
        def to_h: () -> { carrier_name: String, tracking_id: String }
      end

      def get_return: (String) -> Peddler::Response
      def list_returns: (?return_location_id: String?, ?rma_id: String?, ?status: String?, ?reverse_tracking_id: String?, ?created_since: String?, ?created_until: String?, ?last_updated_since: String?, ?last_updated_until: String?, ?last_updated_after: String?, ?last_updated_before: String?, ?max_results: Integer?, ?next_token: String?) -> Peddler::Response
    end
  end
end
