module Peddler
  module APIs
    class FulfillmentOutbound20200701 < API
      def get_fulfillment_preview: (untyped) -> Peddler::Response
      def delivery_offers: (untyped) -> Peddler::Response
      def list_all_fulfillment_orders: (?query_start_date: String, ?next_token: String) -> Peddler::Response
      def create_fulfillment_order: (untyped) -> Peddler::Response
      def get_package_tracking_details: (?package_number: Integer, ?amazon_fulfillment_tracking_number: String) -> Peddler::Response
      def list_return_reason_codes: (String, ?marketplace_id: String, ?seller_fulfillment_order_id: String, ?language: String) -> Peddler::Response
      def create_fulfillment_return: (untyped, String) -> Peddler::Response
      def get_fulfillment_order: (String) -> Peddler::Response
      def update_fulfillment_order: (untyped, String) -> Peddler::Response
      def cancel_fulfillment_order: (String) -> Peddler::Response
      def submit_fulfillment_order_status_update: (String, untyped) -> Peddler::Response
      def get_features: (String) -> Peddler::Response
      def get_feature_inventory: (String, String, ?next_token: String, ?query_start_date: String) -> Peddler::Response
      def get_feature_sku: (String, String, String) -> Peddler::Response
    end
  end
end
