module Peddler
  module APIs
    class SolicitationsV1 < API
      def get_solicitation_actions_for_order: (String, Array[String], ?rate_limit: Float) -> Peddler::Response
      def create_product_review_and_seller_feedback_solicitation: (String, Array[String], ?rate_limit: Float) -> Peddler::Response
    end
  end
end
