module Peddler
  module APIs
    class Tokens20210301 < API
      def self.typed: () -> singleton(Tokens20210301)
      def create_restricted_data_token: (Hash[untyped, untyped], ?rate_limit: Float) -> Peddler::Response
    end
  end
end
