module Peddler
  module APIs
    class VendorTransactionStatusV1 < API
      def self.typed: () -> singleton(VendorTransactionStatusV1)
      def get_transaction: (String, ?rate_limit: Float) -> Peddler::Response
    end
  end
end
