module Peddler
  module APIs
    class VendorDirectFulfillmentPaymentsV1 < API
      def self.typed: () -> singleton(VendorDirectFulfillmentPaymentsV1)
      def submit_invoice: (Hash[untyped, untyped], ?rate_limit: Float) -> Peddler::Response
    end
  end
end
