module Peddler
  module Types
    module Replenishment20221107
      class ErrorList < Data
        def self.new: (errors: Array[Peddler::Types::Replenishment20221107::Error]?) -> Peddler::Types::Replenishment20221107::ErrorList
                    | (Array[Peddler::Types::Replenishment20221107::Error]?) -> Peddler::Types::Replenishment20221107::ErrorList

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::Replenishment20221107::ErrorList

        attr_reader errors: Array[Peddler::Types::Replenishment20221107::Error]?

        def to_h: () -> { errors: Array[Peddler::Types::Replenishment20221107::Error]? }
      end
    end
  end
end
