module Peddler
  module Types
    module Replenishment20221107
      class ListOfferMetricsRequestFilters < Data
        def self.new: (marketplace_id: String?, program_types: Array[untyped]?, time_interval: Peddler::Types::Replenishment20221107::TimeInterval?, time_period_type: String?, ?aggregation_frequency: String?, ?asins: Array[String]?) -> Peddler::Types::Replenishment20221107::ListOfferMetricsRequestFilters
                    | (String?, Array[untyped]?, Peddler::Types::Replenishment20221107::TimeInterval?, String?, String?, Array[String]?) -> Peddler::Types::Replenishment20221107::ListOfferMetricsRequestFilters

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::Replenishment20221107::ListOfferMetricsRequestFilters

        attr_reader aggregation_frequency: String?
        attr_reader asins: Array[String]?
        attr_reader marketplace_id: String?
        attr_reader program_types: Array[untyped]?
        attr_reader time_interval: Peddler::Types::Replenishment20221107::TimeInterval?
        attr_reader time_period_type: String?

        def to_h: () -> { marketplace_id: String?, program_types: Array[untyped]?, time_interval: Peddler::Types::Replenishment20221107::TimeInterval?, time_period_type: String?, aggregation_frequency: String?, asins: Array[String]? }
      end
    end
  end
end
