module Peddler
  module Types
    module Vehicles20241101
      class EngineOutput < Data
        attr_reader value: Float
        attr_reader unit: String

        def self.parse: (Hash[String, untyped] hash) -> instance

        def initialize: (
          value: Float,
          unit: String
        ) -> void
      end
    end
  end
end
