module Peddler
  module Types
    module OrdersV0
      class GetOrderAddressResponse < Data
        def self.new: (?errors: Array[Peddler::Types::OrdersV0::Error]?, ?payload: Peddler::Types::OrdersV0::OrderAddress?) -> Peddler::Types::OrdersV0::GetOrderAddressResponse
                    | (Array[Peddler::Types::OrdersV0::Error]?, Peddler::Types::OrdersV0::OrderAddress?) -> Peddler::Types::OrdersV0::GetOrderAddressResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::OrdersV0::GetOrderAddressResponse

        attr_reader errors: Array[Peddler::Types::OrdersV0::Error]?
        attr_reader payload: Peddler::Types::OrdersV0::OrderAddress?

        def to_h: () -> { errors: Array[Peddler::Types::OrdersV0::Error]?, payload: Peddler::Types::OrdersV0::OrderAddress? }
      end
    end
  end
end
