module Peddler
  module Types
    module OrdersV0
      class OpenInterval < Data
        def self.new: (?end_time: Peddler::Types::OrdersV0::OpenTimeInterval?, ?start_time: Peddler::Types::OrdersV0::OpenTimeInterval?) -> Peddler::Types::OrdersV0::OpenInterval
                    | (Peddler::Types::OrdersV0::OpenTimeInterval?, Peddler::Types::OrdersV0::OpenTimeInterval?) -> Peddler::Types::OrdersV0::OpenInterval

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::OrdersV0::OpenInterval

        attr_reader end_time: Peddler::Types::OrdersV0::OpenTimeInterval?
        attr_reader start_time: Peddler::Types::OrdersV0::OpenTimeInterval?

        def to_h: () -> { end_time: Peddler::Types::OrdersV0::OpenTimeInterval?, start_time: Peddler::Types::OrdersV0::OpenTimeInterval? }
      end
    end
  end
end
