module Peddler
  module Types
    module OrdersV0
      class PackageDetail < Data
        def self.new: (carrier_code: String?, order_items: Array[Peddler::Types::OrdersV0::ConfirmShipmentOrderItem]?, package_reference_id: String?, ship_date: String?, tracking_number: String?, ?carrier_name: String?, ?ship_from_supply_source_id: String?, ?shipping_method: String?) -> Peddler::Types::OrdersV0::PackageDetail
                    | (String?, Array[Peddler::Types::OrdersV0::ConfirmShipmentOrderItem]?, String?, String?, String?, String?, String?, String?) -> Peddler::Types::OrdersV0::PackageDetail

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::OrdersV0::PackageDetail

        attr_reader carrier_code: String?

        attr_reader carrier_name: String?
        attr_reader order_items: Array[Peddler::Types::OrdersV0::ConfirmShipmentOrderItem]?
        attr_reader package_reference_id: String?
        attr_reader ship_date: String?

        attr_reader ship_from_supply_source_id: String?
        attr_reader shipping_method: String?
        attr_reader tracking_number: String?

        def to_h: () -> { carrier_code: String?, order_items: Array[Peddler::Types::OrdersV0::ConfirmShipmentOrderItem]?, package_reference_id: String?, ship_date: String?, tracking_number: String?, carrier_name: String?, ship_from_supply_source_id: String?, shipping_method: String? }
      end
    end
  end
end
