module Peddler
  module Types
    module OrdersV0
      class TaxClassification < Data
        def self.new: (?name: String?, ?value: String?) -> Peddler::Types::OrdersV0::TaxClassification
                    | (String?, String?) -> Peddler::Types::OrdersV0::TaxClassification

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::OrdersV0::TaxClassification

        attr_reader name: String?
        attr_reader value: String?

        def to_h: () -> { name: String?, value: String? }
      end
    end
  end
end
