module Peddler
  module Types
    module Tokens20210301
      class CreateRestrictedDataTokenResponse < Data
        def self.new: (?expires_in: Integer?, ?restricted_data_token: String?) -> Peddler::Types::Tokens20210301::CreateRestrictedDataTokenResponse
                    | (Integer?, String?) -> Peddler::Types::Tokens20210301::CreateRestrictedDataTokenResponse

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::Tokens20210301::CreateRestrictedDataTokenResponse

        attr_reader expires_in: Integer?
        attr_reader restricted_data_token: String?

        def to_h: () -> { expires_in: Integer?, restricted_data_token: String? }
      end
    end
  end
end
