module Peddler
  module Types
    module FBAInventoryV1
      class ResearchingQuantity < Data
        def self.new: (?researching_quantity_breakdown: Array[Peddler::Types::FBAInventoryV1::ResearchingQuantityEntry]?, ?total_researching_quantity: Integer?) -> Peddler::Types::FBAInventoryV1::ResearchingQuantity
                    | (Array[Peddler::Types::FBAInventoryV1::ResearchingQuantityEntry]?, Integer?) -> Peddler::Types::FBAInventoryV1::ResearchingQuantity

        def self.parse: (?Hash[String | Symbol, untyped], **untyped) -> Peddler::Types::FBAInventoryV1::ResearchingQuantity

        attr_reader researching_quantity_breakdown: Array[Peddler::Types::FBAInventoryV1::ResearchingQuantityEntry]?
        attr_reader total_researching_quantity: Integer?

        def to_h: () -> { researching_quantity_breakdown: Array[Peddler::Types::FBAInventoryV1::ResearchingQuantityEntry]?, total_researching_quantity: Integer? }
      end
    end
  end
end
